### ISSUE TITLE
[Feature] Western Cape Breakdown

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#103]
We can now start attempting to infer western cape district breakdowns. See statements by premier here https://www.westerncape.gov.za/department-of-health/news

**Comment by vukosim** [comment]
Example breakdown for 28 03 2020

![image](https://user-images.githubusercontent.com/836223/77853339-f202b500-71e3-11ea-9896-d95cd1029f93.png)

**Comment by nikrich** [comment]
I amazing! Probably need to group these correctly otherwise the data folder is going to become a mess. I'll submit a PR with proposed structure

**Comment by nikrich** [comment]
PR as referred to above: https://github.com/dsfsi/covid19za/pull/104

**Comment by nikrich** [comment]
I think we can close this issue @vukosim

**Comment by webdevan** [comment]
I've created a PR. Please will someone have a look?

I've also got JSON polygons for each of these districts and sub-districts. If that's useful I can create a new issue for it?

**Comment by vukosim** [comment]
@webdevan where do the polygons come from?

**Comment by webdevan** [comment]
@vukosim the polygons are from:
http://www.demarcation.org.za/site/shapefiles/

I've done some work to simplify them (to reduce file size) and mapped them to districts. I am working on Western Cape "heat map" side project which I hope to launch this weekend and I'll share the code/data/info.

The Western Cape numbers come from:
https://www.westerncape.gov.za/department-of-health/news

**Comment by webdevan** [comment]
@vukosim, I came up with this csv for districts and it can allow for more regions to be added later.
https://github.com/webdevan/covid-map/blob/master/data/infections_timeline_za.csv

I thought it would be easier to capture numbers in one file, but if it makes sense I could remove the provinces because they don't need to exist in two places.

Does the structure I used in my repo work for this project? With the geoJSON files? If so I can submit a PR.
https://github.com/webdevan/covid-map/blob/master/data/

**Comment by vukosim** [comment]
For the moment would keep the csv as is. We can create a script to read from yours and create a pull request with additions on the district csv here

The GegJSOn would be appreciated.

**Comment by webdevan** [comment]
@vukosim please grab the .json files (and anything else you like) from here: https://github.com/webdevan/covid-map/blob/master/data/

I'm not sure where they should go and have limited free time so it's best if you can do it.

I'll probably ditch the timeline csv in my repo and just pull the covid19za ones instead.

**Comment by vukosim** [comment]
Thank you. Yeah, also battling with thin time. Will look who I can ask to assist. @webdevan Thank you.

**Comment by riazarbi** [comment]
Please comment on #180 if you have the time.

**Comment by webdevan** [comment]
@vukosim can we close this issue?

**Comment by vukosim** [comment]
Thanks @webdevan
