### ISSUE TITLE
[Feature] CSV to google sheet sync tool

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#108]
We run the dashboard on top of google sheets and now are in need of a way to automate a csv to google sheet sync. Assume that the google sheets have the same name as the csv files.

**Comment by anelda** [comment]
It's possible in R... https://googlesheets4.tidyverse.org/

**Comment by anelda** [comment]
I can write something if it is okay that it is written in R. Do you need it to pull the sheet down or only push the csv to the sheet and overwrite the data that was there previously?

**Comment by vukosim** [comment]
Overwrite is fine.

**Comment by riazarbi** [comment]
Y'all are overthinking this. 

`=importData("https://raw.githubusercontent.com/dsfsi/covid19za/master/data/covid19za_provincial_cumulative_timeline_confirmed.csv")`

Apparently the importData function lasts for 1 hour, giving you free refreshes, but if it doesn't we can write a script trigger in google sheets.

**Comment by anelda** [comment]
If I understand correctly, the scraper will create a CSV file which is available from the github repo. We need a way to update the Google Sheet from the CSV in the Github repo. @riazarbi if you have a simple solution, please create a pull request or discuss further with @vukosim. I think at this stage they will prefer simple, robust methods to ensure clear data provenance so you might very well have a better solution than mine. 

In the meantime I've written a very simple script available at https://github.com/anelda/covid19za_misc/blob/master/sync_csv_google_ss.R which may be useful?  I'm not sure what your workflow is to update the CSV or how you prefer to update the Google Sheet so it's a bit tricky to come up with something useful. Let me know if this script might work and if I can do something to improve it?

**Comment by anelda** [comment]
Oh @riazarbi I remember now, one can simply put your function in the first cell of the target Google Sheet to import the table at the source CSV. Haven't used that in ages. Yes, may work!

**Comment by riazarbi** [comment]
Yep, just pop that function in a google sheet cell. Let me know if you have trouble.

**Comment by vukosim** [comment]
Thanks guys. Worked, just need to get a script going to pull every hour or so.

**Comment by riazarbi** [comment]
Just double check it doesn’t do it every hour automatically.  It should.
More frequent will require a script.

**Comment by anelda** [comment]
@vukosim I experimented with Google scripts to automate, but there were a few things that felt a bit like a black box. I've updated the R script so that you can run it from the commandline as cron job. It's at https://github.com/anelda/covid19za_misc/blob/master/syncGoogleCovidza.R.

It includes instructions for getting auth from R for Google Sheets (see comments in script). I can add it to this repo via PR if you think it is useful?

**Comment by vukosim** [comment]
Thanks guys, closing this. The importData is working great.
