### ISSUE TITLE
[Feature] Track cumulative number of tests results for each day

### ISSUE THREAD

**Issue by rendanim** [dsfsi/covid19za#111]
Is it possible to display the time series of the cumulative of test results on each day. This will contextualise the positives cases. For example if they are slowing down because the number of test are also slowing down i.e backlog? 

The graph can look just like the confirmed cases graph. Just for one to see if the decrease is due to the decrease in test results..per day.

**Comment by vukosim** [comment]
Hey @rendanim we have been working on that, just updated the front page.

**Comment by rendanim** [comment]
Fantastic! Thanks.
