### ISSUE TITLE
[Feature]Data provenance and giving due credit for datasets

### ISSUE THREAD

**Issue by anelda** [dsfsi/covid19za#117]
**Is your feature request related to a problem? Please describe.**
We are collecting data from a wide variety of sources and also data that is available under a variety of licenses (or without licenses)

**Describe the solution you'd like**
Figure out a way to keep track of data sources and a way to ensure proper credit is given to people/organisations who have collected the data and are willing to share it.

**Describe alternatives you've considered**
Everyone who is contributing data may not be familiar with Github. Maybe create a short Google Form that can be completed by data donors/contributers/collectors. 

**Additional context**
There must be value in it for people to contribute data. In many cases the datasets that we want to combine with case data has taken a lot of time and/or money to collect. This is a great opportunity to highlight work that has been done by people supporting the notion of open data and open science in the hope that they will get recognition/opportunities beyond just doing good for the greater good of mankind. 

See e.g. this thread from Our World in Data - https://twitter.com/maxcroser/status/1243938224780783616

**Comment by vukosim** [comment]
The data/README.md has all the info on all sources of the data. Can we enhance that?

**Comment by vukosim** [comment]
The data/README.md has all the info on all sources of the data. Can we enhance that?

**Comment by anelda** [comment]
I suggest that we make it mandatory for all CSV files to have the following columns:

- last_updated_day (not the csv file but the actual source data - may not be available)
- last_updated_month (not the csv file but the actual source data - may not be available)
- last_updated_year (not the csv file but the actual source data - may not be available - but effort to get good guesstimate)
- source (could be url or other, but preferrably url - might not be available)
- source_name (person who created the dataset - if available)
- source_surname (if available)
- source_phone (if available)
- source_email (if available)

I know this seems like a lot of extra columns, but it will really be valuable if we have to go back to a source or if the media would like to contact one of the sources to do a story about the value of a dataset, or if there are questions about the data. 

And it will really make a great story if we can write a post after everything about where the data came from and how valuable open datasets are.

**Comment by webdevan** [comment]
A CSV could contain data from multiple sources and it might get messy to add in metadata with actual data. What about a separate text file in the same directory as the CSV file, eg a README.md or LICENSE.md or something along those lines. The text file can contain all the attribution and background info that is relevant to the datasets?

**Comment by anelda** [comment]
Hi @webdevan! Great point. I was working on the hospital data this weekend and realised my suggestion will not work exactly because of the things you mentioned. And THANKS for reminding us of metadata... We should/could create machine-readible metadata schema files for each of the CSV files as well to describe the columns. And here we can add some information about sources as well? 

Here is an example - https://github.com/digital-preservation/csv-schema/blob/master/example-schemas/digitised_surrogate_tech_acq_metadata_v1_TESTBATCH000.csvs 

I think the readmes is a good start combined with a machine-readable metadata schema file it becomes more powerful. And of course if we also share the scripts that took us from raw data to tidy/complete data it will be possible to trace the origin of different cells within the final dataset.
