### ISSUE TITLE
Missing 10 Confirmed Cases 15 March

### ISSUE THREAD

**Issue by Ofentswe1** [dsfsi/covid19za#12]
@vukosi we have new 10 cases confirmed but not yet out on gov.za (total should now be 61)

**Comment by vukosim** [comment]
@Ofentswe1 we need to have the official statement so that we can update. So far only the presidents number. We can make a decision later this afternoon about adding empty cases to match with the presidents numbers.

**Comment by Ofentswe1** [comment]
@vukosi, Yes we can,  I have also used the WhatsApp bot and I saw a new case in Limpopo, we will wait for official statement to make decision later

**Comment by vukosim** [comment]
Added 10 cases from the Whatsapp statement. 

Do not have demogrpahic information and transmission type so left empty

**Comment by vukosim** [comment]
Official statement out. 11 cases updated https://sacoronavirus.co.za/2020/03/16/statement-by-the-minister-covid-19-16-march-2020/

**Comment by Ofentswe1** [comment]
Thanks @vukosim
