### ISSUE TITLE
[Feature] provincial_cumulative_timeline_confirmed

### ISSUE THREAD

**Issue by ahmadalauddin** [dsfsi/covid19za#122]
Can you please add the API endpoint to provide the provincial cumulative timeline confirmed data, just like the data you are showing in the csv file but in JSON format? 

Thanks in advance!

**Comment by Vutlhari** [comment]
I will pick this up

**Comment by Vutlhari** [comment]
@ahmadalauddin this endpoint is now available. Please test and confirm.

Endpoint: https://covid-za-api.herokuapp.com/cases/timeline/provincial/cumulative

**Comment by ahmadalauddin** [comment]
Thank you very much. I really appreciate your help in this regard. I have tested it and it is returning the results just fine, however there is an issue with the no of unknowns. The unknowns are returning the same number as Western Cape. Can you please look into it?

**Comment by Vutlhari** [comment]
> he unknowns are returning the same number as Western Cape. Can you ple

Sure, will take a look :)

**Comment by Vutlhari** [comment]
@ahmadalauddin the issue with unknowns returning the same number as Western Cape should be fixed now. Thanks for picking this up :)

**Comment by ahmadalauddin** [comment]
Thank you so much. I have tested the API and it is working perfectly. Thanks a lot again!!
