### ISSUE TITLE
[Feature] Distinguish recoveries vs new positive cases on the "Daily Positive Cases" chart

### ISSUE THREAD

**Issue by omicron-c** [dsfsi/covid19za#123]
At the moment, the label "Daily Change in Positive Cases" appears misleading. Change can happen in both additive and subtractive fashions. I believe you are including positive delta movements (new cases), and not negative (Recoveries) movements in this chart. 

This is a guess I am making by looking at your March 27th figure of 243 new cases (As the Gov press release notes), when if it were inclusive of recoveries, would be at 213 (minus the 30 recoveries). 

I believe this will be more and more important as the number of recoveries increases on a daily basis.

**Comment by HoosainEssop** [comment]
I have completed this enhancement and updated the notebook: https://github.com/dsfsi/covid19za/blob/master/notebooks/COVID-19%20South%20Africa%20-%20Data%20Analysis%20and%20Visualization.ipynb
