### ISSUE TITLE
[Feature] Hospital and district data for visualisation

### ISSUE THREAD

**Issue by MikeMcMalace** [dsfsi/covid19za#13]
Currently, there are fragmented and limited consolidated public data regarding the healthcare systems in South Africa. This extends beyond just knowing about a particular hospital but also relates to functions of the hospital such as specialised care, location, the estimated population in the district, and which hospitals can potentially assist in the COVID-19 pandemic. 

To combat this, hospitals with specialised staff/units are available in South Africa, but this knowledge is not always accessible to the general public. Furthermore, this data seems to be in different formats, depending on the province/district and is not consolidated on one platform which makes data analysis challenging related to resource management.

I propose that we collate all the hospital data within South Africa so that we can have a clear visualisation of maximum capacity, and have data available so that other data scientists can perform assessments related to resource management, projections per district and identify what COVID-19 hotspots mean in terms of hospital capacity. 

To do this, we need to start by collating data per province, related to the location of the hospital,  and capability of the hospital.
1)	Location of hospital 
a.	Name of hospital
b.	GPS coordinates
c.	Province
d.	District
e.	Subdistrict
f.	Estimated population within the district
2)	Capacity and capability
a.	Description of the hospital (each type of hospital has its own detail)
b.	Size (differs per hospital type for example small district is 50 – 150 beds, small tertiary is 400)
c.	Operational functions (services which must be included within the type of hospital)
d.	Type of hospital (district, regional, tertiary, central or specialized)
e.	Maximum capacity
f.	Speciality services (what specialised services are at the hospital, for example, internal medicine and infectious disease units etc.)
g.	Can the hospital currently respond to COVID-19?
h.	Source confirming the hospital can currently respond to COVID-19
i.	CEO of hospital
j.	Postal address of hospital
k.	The physical address of the hospital
l.      Contact number
m.    Email

The last question “Can the hospital currently respond to COVID-19?” is challenging to answer unless public statements have been made. We know that the following hospitals are/were highlighted as quarantine hospitals.

Province	HosptName	                          GPSCoordinant	         TotalHospitalBeds
Limpopo	Polokwane Hospital	         23.8968° S, 29.4574° E	450
Mpumalanga	Rob Ferreira Hospital	25.4769° S, 30.9709° E	461
Gauteng	Charlotte Maxeke Hospital	26.1760° S, 28.0439° E	1088
Gauteng	Steve Biko Academic Hospital  25.7303° S, 28.2044° E	832
Gauteng	Tembisa Hospital	                  25.9830° S, 28.2382° E	840
KwaZulu Natal	Grey's Hospital	          29.5795° S, 30.3643° E	530
North West	Klerksdorp Hospital	26.8789° S, 26.6633° E	890
Northern Cape	Kimberely Hospital	28.7462° S, 24.7730° E	287
Free State	Pelonomi Hospital	         29.1396° S, 26.2447° E	469
Eastern Cape	Livingstone Hospital	 33.9254° S, 25.5697° E	541
Western Cape	Tygerberg Hospital	          33.9106° S, 18.6123° E	1384

We also know, based on articles written about each one of these hospitals, that they experience a heavy load of patients throughout the year – irrespective of COVID-19.

The data that is consolidated can be used as a dashboard for the general public to see where they can go in terms of public healthcare, and additionally, other scientists can use this data to make contextually relevant inferences if they have this data and add it to their analysis.

**Comment by MikeMcMalace** [comment]
[16_03_2020_KZNHospitalDatabase.xlsx](https://github.com/dsfsi/covid19za/files/4338027/16_03_2020_KZNHospitalDatabase.xlsx)

**Comment by vukosim** [comment]
See health_system_za_public* files in data/

populating with a few examples is needed.

**Comment by MikeMcMalace** [comment]
The Department of Health for each South African province has this data, but it is scattered and there is not consistent format between the different departments. Consolidating this information as a dataset will be valuable for visualisation as well as for analytics related to capacity and systems.

**Comment by vukosim** [comment]
See 

General: https://github.com/dsfsi/covid19za/blob/master/data/health_system_za_public_hospitals.csv
Detailed: https://github.com/dsfsi/covid19za/blob/master/data/health_system_za_public_hospitals_extended_details.csv
Contacts: https://github.com/dsfsi/covid19za/blob/master/data/health_system_za_public_hospitals_contacts.csv

**Comment by vukosim** [comment]
@MikeMcMalace See latest commit to branch Hospital_data

**Comment by vukosim** [comment]
Think now getting per hospital ICU is next

Also thanks @elolelo

**Comment by MikeMcMalace** [comment]
Thank you Nompumelelo, this is great!

**Comment by vukosim** [comment]
You might also want to dig into https://opendataza.gitbook.io/toolkit/open-data-resources/healthcare-data-resources

@elolelo and @MikeMcMalace

**Comment by vukosim** [comment]
Hey @MikeMcMalace how are we doing here?

**Comment by MikeMcMalace** [comment]
Her @vukosim , currently with regard to the district data we have 351 hospitals, with complete data except for 2 with missing geodata. Unfortunately, name changes etc. complicate this a bit. 
[20_03_2020_CurrentHospitalData_12_05pm.xlsx](https://github.com/dsfsi/covid19za/files/4358894/20_03_2020_CurrentHospitalData_12_05pm.xlsx)

**Comment by vukosim** [comment]
@MikeMcMalace please see the Hospital Data branch. I would suggest you work on that as it also has info on where the data came from as per @elolelo

**Comment by vukosim** [comment]
See https://w.wiki/Ksn

**Comment by MikeMcMalace** [comment]
Fantastic! Is this linked?

**Comment by vukosim** [comment]
The data on that link is from WIkiData. So wikidata would have to be updated. We have a volunteer from Codebridge who says they will update during the week.

**Comment by ksharpeypd** [comment]
and apologies if you already have this, but there's quite detailed descriptions of each facility (down to the ward level? not sure about capacity) here on the NIDS site:
https://dd.dhmis.org/orgunits.html?file=NIDS%20Integrated&source=nids

**Comment by elolelo** [comment]
@MikeMcMalace Hey Mike, did you get a chance to check this out?

**Comment by MikeMcMalace** [comment]
Yes. Unfortunately, there are some issues in the data (unless they updated it within the last day). The biggest problem is district information and bed capacity. Each district hospital (according to the South African DoH) is categorised as either small, medium or large. In addition to this, each district has its own capacity (or estimated capacity). The hospital data have been updated, and thank you @elolelo for your valuable contribution into this matter. The problem right now is we want to have certain information on a map, that details the hospital, what it can and cannot do, and have information about the district included in it.

Something similar to this:  https://codebridge-za.github.io/seeking-shelter/index.html

but with the details of this: https://www.healthestablishments.org.za/Home/Facility

and with the added district data and information about the hospital capacity.

The reason for this is we know which hospitals are COVID-19 ready. We also have amazing tools like the links here, which are very useful, but not if you have a medical emergency other than COVID-19, or COVID-19. When doing this search, I was shocked at how much digging one needs to do, not just for South Africa, but in general in Africa to find this information. The idea is to consolidate information in a way that is useful and usable to a person who is not a tech enthusiast, and who just has a cellphone.

**Comment by elolelo** [comment]
This is being addressed in #115
