### ISSUE TITLE
[Feature] SA COVID Project: Vulnerable Communities Map

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#14]
**Describe the solution you'd like**
See https://www.offerzen.com/blog/sa-covid-19-project-vulnerable-communities-map

If there are interesting datasets, please do make them available to Offerzen as well as make them available here.

**Comment by Baadier-Sydow** [comment]
For some reason your link when clicked doesnt take you to the blog post. 

https://www.offerzen.com/blog/sa-covid-19-project-vulnerable-communities-map

Looks like the 19 is missing from yours.

**Comment by vukosim** [comment]
Think they changed it after. Will fix

**Comment by Baadier-Sydow** [comment]
Sweet :)

**Comment by elolelo** [comment]
@vukosim Did you get a chance to fix the link in question? Is it now working?

**Comment by vukosim** [comment]
Thanks @elolelo Yes fixed. Will close.
