### ISSUE TITLE
[Feature] Limpopo District Data

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#145]
See this 
![image](https://user-images.githubusercontent.com/836223/78573859-8050e980-7829-11ea-8be9-92d973b91ee3.png)

We need to now create a CSV file for the Limpopo data. Currently tracing that we can get this on the regular.

**Comment by vukosim** [comment]
First version is up in district folder. Need to code subdistricts.

**Comment by SefaraTJ** [comment]
Was this picture on twitter of FB? Posted by who?

**Comment by vukosim** [comment]
https://www.facebook.com/LimpopoDepartmentOfHealthBophelong/

https://www.facebook.com/photo?fbid=2484848634949084&set=a.442368809197087

**Comment by SefaraTJ** [comment]
CSV for above pic is created?

**Comment by vukosim** [comment]
See https://github.com/dsfsi/covid19za/blob/master/data/district_data/provincial_lp_cumulative.csv

but maybe we can use the full district and subdistrict names on the columns. @SefaraTJ

**Comment by SefaraTJ** [comment]
Sekhukhune is a missing district. To add subdistrict/municipality, then the current format should be upgraded to.
- columns [**district**, **subdistrict**, **date** ]
_I'm surprised mokopane is district!!_

**Comment by vukosim** [comment]
Same here. 

Date should be the first column. 

patten should b

data, district1, district1_subdistrict1, district1_subdistrict2,district1_subdistrict3, district2_subdistrict1,district2_subdistrict2

@SefaraTJ

**Comment by vukosim** [comment]
@JosephSefara Can you add a source column to the csv at the end, as well as a total column.
