### ISSUE TITLE
[Feature] Mpumalanga District Data

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#147]
See example 

![image](https://user-images.githubusercontent.com/836223/78577022-c019d000-782d-11ea-801e-35adf66c0edb.png)

**Comment by henkhodryza** [comment]
Please assign me to do this

**Comment by vukosim** [comment]
@henkhodryza Done. Please also upload the files you use (pdfs or pictures) into the document folder. You can just name them the data-mpumalanga-district etc.

**Comment by HoosainEssop** [comment]
Good day. I have worked on a solution using AWS Textract. As shown in the attachment. Although it should be said that if the layout of the image changes with future releases/posts on Facebook or other social media then the script would have to be adjusted to handle those changes.![MPDistrictData](https://user-images.githubusercontent.com/40713765/79553929-966a6f80-809d-11ea-8914-438698eb56e8.png)

![Example](https://user-images.githubusercontent.com/40713765/79554111-e3e6dc80-809d-11ea-8ea4-c3305e9bda8b.JPG)
