### ISSUE TITLE
[Feature] Data Access API

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#15]
**Describe the solution you'd like**
API to access the data easily.

@Vutlhari is working on this.

**Comment by kaysiz** [comment]
@vukosim is the API project open, if so share so we can contribute where necessary

**Comment by vukosim** [comment]
@Vutlhari has finished version 1, just waiting for him to do the pull request here. Then you can assist.

**Comment by vukosim** [comment]
Version 1.0 now available https://github.com/dsfsi/covid19za/tree/master/api

**Comment by Baadier-Sydow** [comment]
@vukosim I'm working on parsing the data files and then making it publicly available via an open API. Will update here when it's done. It will likely be quick and dirty for now as I want to get it up this weekend.

**Comment by Vutlhari** [comment]
Hi @Baadier-Sydow is there a specific reason why you want to develop a separate API?

**Comment by Baadier-Sydow** [comment]
I mostly wanted to deploy it somewhere and have it be publicly accessible while being able to extend it. I wasn't familiar with the tech that your API is done in and I don't think you have it up somewhere?

**Comment by Vutlhari** [comment]
It's hosted [here](https://covid-za-api.herokuapp.com/cases/confirmed?province=LP), I updated the [README](https://github.com/dsfsi/covid19za/tree/master/api) yesterday. I also added a Dockerfile to ensure that it can be hosted on any platform that supports containers. :)

**Comment by Baadier-Sydow** [comment]
Awesome!! I'll give it a try :)

**Comment by vukosim** [comment]
I am closing this.
