### ISSUE TITLE
[Feature] Data Source for global confirmed, recovered and death data (includes daily updates on South Africa0

### ISSUE THREAD

**Issue by HoosainEssop** [dsfsi/covid19za#151]
**Is your feature request related to a problem? Please describe.**
The source contains data in CSV format that can be used for analysis on confirmed, recovered and fatal cases:

https://data.humdata.org/dataset/novel-coronavirus-2019-ncov-cases

**Comment by vukosim** [comment]
Thanks @HoosainEssop that data comes from a source that is keeping overall numbers and does not really work on validation of those numbers (they have many errors). It is okay to automatically pull from it for analysis but we won't be adding their data to this repo.
