### ISSUE TITLE
[BUG] : Clutered Plot - Total tests performed

### ISSUE THREAD

**Issue by Ari-Ramkilowan** [dsfsi/covid19za#154]
**Describe the bug**
The total tests performed plot has 5 digit (soon 6 digit) numbers. These overlap on the plot and makes the plot unreadable. This information is also duplicated by the information displayed when you hover on a point. 

**To Reproduce**

Nothing required, just have to view the plot on the dashboard

**Expected behavior**
A clear , easy-to-read plot

**Screenshots**
![Screenshot from 2020-04-09 10-27-25](https://user-images.githubusercontent.com/33620500/78874518-ccc83f00-7a4c-11ea-8dbd-413b8a3fd515.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser : Firefox
 - Version 74 (6 bit)

**Comment by vukosim** [comment]
Cleaned up a bit @Ari-Ramkilowan
