### ISSUE TITLE
[DATA] Error in plot

### ISSUE THREAD

**Issue by mattia-vaccari** [dsfsi/covid19za#155]
## Which Dataset
Total Tests Performed (see attachment)

<img width="678" alt="Screenshot 2020-04-09 at 13 04 55" src="https://user-images.githubusercontent.com/7235807/78888909-e8d6db00-7a62-11ea-81ff-4402402cc44e.png">

## Error Description

For some reason, total test performed numbers now show up as 600,000 rather than ~63,000 IIRC.

## Suggested fixes
Should be trivial

**Comment by vukosim** [comment]
Fixed. Thanks @mattia-vaccari
