### ISSUE TITLE
[Feature] Gauteng District Data

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#156]
![image](https://user-images.githubusercontent.com/836223/78897990-55f26c80-7a73-11ea-844d-3b4faef2d3eb.png)

Source https://www.facebook.com/ward56.jhbsouth/photos/a.1786382144979883/2637016066583149/?type=3

Need to create csv for all regions. Put in data/district_data/

**Comment by vukosim** [comment]
![image](https://user-images.githubusercontent.com/836223/78898198-b41f4f80-7a73-11ea-9b18-02ba0f0677e6.png)

**Comment by codeChap** [comment]
Any specific structure required or can I just go for it?

**Comment by vukosim** [comment]
@codeChap Check the WC format in the district_data folder.

**Comment by vukosim** [comment]
@codeChap 
![image](https://user-images.githubusercontent.com/836223/79038837-de405100-7bdc-11ea-9579-a54c0d86ee23.png)

**Comment by vukosim** [comment]
Just got a note from a spokesperson that the first 2 cannot be used as they are not verified. Created a file with gauteng regions. CLosing this.
