### ISSUE TITLE
[Feature] Notebook to compare SA growth curve to other countries and understand where we are.

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#16]
**Describe the solution you'd like**
There have been comparisons across different groups to track spread since first case. See example [here](https://public.tableau.com/profile/john.alexis.guerra.g.mez?fbclid=IwAR1HSwbCEmpLjcOYKd8VNgUfq3MAHoHVPLu_6Xi-uSz8VVFtG14680NM9MU#!/vizhome/time_series_19-covid-Confirmed/Confirmedcaseslatam?publish=yes)

Can we create this for South Africa vs rest of world
South Africa vs African countries.

**Comment by Ofentswe1** [comment]
The link is unavailable, can you attach it as image if you have it open before refreshing.

**Comment by vukosim** [comment]
Should be working now

**Comment by Ofentswe1** [comment]
I will have a look it and try to replicate similar thing for South Africa

**Comment by vukosim** [comment]
![image](https://user-images.githubusercontent.com/836223/76991385-2eb3ee00-6952-11ea-95a3-0b99668cedd7.png)

If we could do this for SADC and Africa.

**Comment by Ofentswe1** [comment]
Thanks @vukosim

**Comment by vukosim** [comment]
@altadewaal has created a few notebooks on this. Closing.
