### ISSUE TITLE
[BUG] API

### ISSUE THREAD

**Issue by surenkasilsyfinity** [dsfsi/covid19za#164]
## Which Dataset
cases/timeline/tests

## Error Description
The cumulative_tests is reflecting blank, please update your dataset.

Thanks

{
        "date": "07-04-2020",
        "timestamp": "20200407",
        "cumulative_tests": "",
        "recovered": "45",
        "hospitalisation": "",
        "critical_icu": "10",
        "ventilation": "",
        "deaths": "13",
        "contacts": {
            "contacts_identified": "",
            "contacts_traced": ""
        },
        "travellers": {
            "scanned": "",
            "elevated_temperature": "",
            "covid_suspected_criteria": ""
        }

## Suggested fixes
  1.
  1.
  1.

**Comment by vukosim** [comment]
@Vutlhari might you look at this.

**Comment by Vutlhari** [comment]
> @Vutlhari might you look at this.

Will do

**Comment by Vutlhari** [comment]
@vukosim this looks like a data issue, the CSV does not have `cumulative_tests` for `"07-04-2020`. Please see the attached screenshots.

![Issue #164](https://user-images.githubusercontent.com/1713303/79310102-ac402f00-7efb-11ea-8209-2c356ae6453e.png)
![API Response](https://user-images.githubusercontent.com/1713303/79310263-ef9a9d80-7efb-11ea-9b8a-d8c8612aa6da.png)

**Comment by vukosim** [comment]
Ahh yes. It means for that day, we did not get an official statement from the ministry. So we cant put numbers. @surenkasilsyfinity
