### ISSUE TITLE
[Feature] Twitter Data

### ISSUE THREAD

**Issue by Pygario** [dsfsi/covid19za#179]
I have been scraping tweets related to the virus in South Africa (just #Covid19SA so far but planning on doing more) for a personal project I am working on and I was wondering if you might have use for this data?

I am currently sitting with about 14000 tweets, going back to the 5th of April, in a CSV file(it's a bit dirty).

I am working on a sentiment analysis project so I will be getting as much data as I can and I am more than happy to share.

**Comment by vukosim** [comment]
@Pygario We do have this data that we have collected and have ethical clearance for at the university.
