### ISSUE TITLE
[Feature] Add airport scan data and other data from NICD situational reports

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
See reports [here](http://www.nicd.ac.za/diseases-a-z-index/covid-19/covid-19-situational-reports/). We need the numbers per day in csv format.

**Comment by elolelo** [comment]
@vukosim Are you looking for some help with converting the daily numbers from the NICD reports to  to a csv format? And also, do you have the airport scan data?

**Comment by vukosim** [comment]
Yes. That is the help. We have situational reports until 18 March. If someone can help with creating data out of them.

**Comment by vukosim** [comment]
Closing as this is no longer relevant.
