### ISSUE TITLE
API missplaced keys [BUG]

### ISSUE THREAD

**Issue by henkhodryza** [dsfsi/covid19za#181]
**API data bug**
When you hit the endpoint `/cases/deaths`
"age" and "gender" keys do not have the
corresponding values.
"age" has a string value that belong to "gender"
and "gender" has a integer value that belong to "age"

**To Reproduce**
1. Go to [to this end piont](https://covid-za-api.herokuapp.com/cases/deaths)
2. Check each object of the JSON file
3. You will see the error

**Expected behavior**
Swipe the key values of gender and age

**Comment by vukosim** [comment]
@Vutlhari please check

**Comment by Vutlhari** [comment]
I will take a look 😊

**Comment by Vutlhari** [comment]
This issue was fixed in a previous PR, it was just not deployed for some reason. I have deployed the latest changes. I have tested the deployed version and the mapping now seems alright. Please verify @henkhodryza
