### ISSUE TITLE
[DATA] covid19za_provincial_cumulative_timeline_deaths.csv not getting updated on a regular basis

### ISSUE THREAD

**Issue by 1Map** [dsfsi/covid19za#184]
## Which Dataset
/data/covid19za_provincial_cumulative_timeline_deaths.csv

## Error Description
Although other files are getting updated on a regular basis, this file does not and is behind.

## Suggested fixes
  1. Update this file when you update /data/covid19za_timeline_deaths.csv

**Comment by vukosim** [comment]
@1Map if you could assist with creating a pull request with the data as it becomes available, that will assist a lot.
