### ISSUE TITLE
[Feature] Inconsistency in "province" fields

### ISSUE THREAD

**Issue by bmerry** [dsfsi/covid19za#187]
**Is your feature request related to a problem? Please describe.**
In some places province is a 2-3 letter code (WC, KZN), in some places there is a ZA- prefix (e.g. ZA-WC, ZA-KZN) and in others the full name is used (Western Cape etc). These can be seen [here](https://github.com/dsfsi/covid19za/blob/master/data/covid19za_timeline_confirmed.csv), [here](https://github.com/dsfsi/covid19za/blob/master/data/health_system_za_private_hospitals.csv) and [here](https://github.com/dsfsi/covid19za/blob/master/data/health_system_za_public_hospitals.csv).

Background: I'm not using this data for anything myself, but I have free time so am hoping to help out. I started implementing a province filter for the API for hospitals (listed as a [TODO](https://github.com/dsfsi/covid19za/blob/master/api/README.md#todo) when I discovered this.

**Describe the solution you'd like**
I'm not committed to any particular solution - just pointing out something that might cause frustration for others. Some suggestions below:

**Describe alternatives you've considered**
- Modify the health system data to use the same province format as the case data. Of course, this might break code that is depending on the current format.
- Add an extra column to CSV files that contains the province data in a canonical format (since the case data has "geo_subdivision" for the ZA-XXX format maybe replicate that?). 

**Additional context**
I'm happy to help do some work on this, but I don't know nearly enough about how the data is being collected (manual entry versus scraping) or what is consuming it to know what approach is best or what the implications of changes are.

**Comment by dmackie** [comment]
Please rather add a field such as `geo_subdivision` then change data.  There could be people replying on the naming scheme already.   Also please use standard naming scheme such as https://en.wikipedia.org/wiki/ISO_3166-2:ZA which seems to be used in the one dataset.

**Comment by bmerry** [comment]
Sure, will take a look this weekend. Thanks for the Wikipedia link - I learnt something new.

**Comment by vukosim** [comment]
Thanks @bmerry 
If you fouls assist with proposed changes and put them in the staging folder, that would be great.

**Comment by bmerry** [comment]
I think I've covered everything possible within the constraints of backwards compatibility, so closing.
