### ISSUE TITLE
[Feature] Add municipality to confirmed, deaths and tests datasets

### ISSUE THREAD

**Issue by riazarbi** [dsfsi/covid19za#19]
**Is your feature request related to a problem? Please describe.**
We would like to monitor occurrences on a municipality level

**Describe the solution you'd like**
A new column in the confirmed dataset (at a minimum) stating municipality

**Describe alternatives you've considered**
Contacting the NICD directly. We'll still pursue this, but they are probably swamped.

**Comment by vukosim** [comment]
Hmm. Yeah, until that info is released by an official source [NICD, DoH], we won't put it in here. I have stayed away from news reports as a source for this reason.

**Comment by riazarbi** [comment]
Thanks for replying, I'm sure you guys are swamped. 

Alright, we are reaching out to NICD and DoH separately this week. If we find someone receptive we will ask the if this can be released as well. 

Are you manually parsing your data from the NICD blog posts ([example](http://www.nicd.ac.za/covid-19-update-18/)) or are you getting some sort of data download?

I ask because if we do manage to talk to someone receptive we'd ask if they can start preparing datasets for download and I'd like to make sure I'm not asking for duplicate work.

**Comment by vukosim** [comment]
Thanks for reaching out to NICD. Through other channels, we have also asked for NICD and DoH to have machine-readable files with their posts. 

Currently, it's manual to populate, but a scraper is in a pull-request and waiting for a final readme, so we should be able to do auto scraping by this evening. 

We all hope to find someone receptive. I would love to have them as the data custodians, it will improve the data quality by lots. 

On the comorbidity, let me know once you get an answer if on aggregate the data can be made available.

**Comment by riazarbi** [comment]
Alright, will do. Closing this for now, but will reopen if it becomes feasible in the future.

**Comment by vukosim** [comment]
Given todays announcement by Western cape government, can we start collecting stats on Western cape @riazarbi?

**Comment by riazarbi** [comment]
I don't think a pattern of sharing municipal-level data has been established - I think that was a once-off thing. I don't think I'll be able to be a source of data for this as internal govt researchers are probably going to be prohibited from sharing anything (which is good). 

But, my impression is that the data exists at this level of granularity - so it's a question of getting NICD to release this publicly.

**Comment by webdevan** [comment]
Hey @riazarbi I think a pattern has been established now. It's been daily (almost), and I've done some work to understand a potential data structure, see https://github.com/dsfsi/covid19za/issues/103#issuecomment-609446640

**Comment by riazarbi** [comment]
If anybody would like to comment on #180 I'll take it to whatever channels are open to me

**Comment by vukosim** [comment]
@riazarbi we have now all this data. If you would like to help, take a look at 

data/covid19za_provincial_cumulative_timeline_recoveries.csv
data/covid19za_provincial_cumulative_timeline_testing.csv
data/covid19za_provincial_cumulative_timeline_confirmed.csv
