### ISSUE TITLE
[Feature] Provincial cumulative data for deaths, confirmed cases and recoveries.

### ISSUE THREAD

**Issue by coenraadhuman** [dsfsi/covid19za#191]
I would like to include recoveries for province data on the [https://sacovid.co.za/](https://sacovid.co.za/) dashboard. 

Is there a possibility that a new endpoint or upgraded "/cases/timeline/provincial/cumulative" can be provided?

**Comment by vukosim** [comment]
@Vutlhari please see

@coenraadhuman could you volunteer to also update [covid19za_provincial_cumulative_timeline_deaths.csv](https://github.com/dsfsi/covid19za/blob/master/data/covid19za_provincial_cumulative_timeline_deaths.csv)

and create covid19za_provincial_cumulative_timeline_testing.csv

**Comment by Vutlhari** [comment]
I can take a look 🙂

**Comment by Vutlhari** [comment]
@coenraadhuman please let me know when you've updated the CSV soI can update the API.

**Comment by coenraadhuman** [comment]
Hi all, I won’t be able to update the CSV on a regular basis. So I’ll have to decline the offer.
