### ISSUE TITLE
Latest confirmed cases in provincial cumulative data is incorrect

### ISSUE THREAD

**Issue by shaunsaker** [dsfsi/covid19za#195]
Hi @vukosim! 

First of all, thanks for the awesome work you are all doing!

One of the users of my [App](https://github.com/shaunsaker/covid-19-south-africa-app)  just reported that the latest confirmed cases number is incorrect. It should be **3465** and not 3645.

Thanks again.

**Comment by vukosim** [comment]
Fixed.
