### ISSUE TITLE
[DATA]

### ISSUE THREAD

**Issue by TeeZA42** [dsfsi/covid19za#199]
## Which Dataset
covid19za_provincial_cumulative_timeline_confirmed

## Error Description
2 row entries for 21-04-2020 is this correct? Last one should be 22-04-2020

21-04-2020,20200421,345,106,1199,671,27,24,16,24,1010,43,3465,https://twitter.com/DrZweliMkhize/status/1252631607166500866?s=20
21-04-2020,20200421,377,106,1224,758,27,23,16,24,1079,1,3635,https://sacoronavirus.co.za/2020/04/22/update-on-covid-19-22nd-april-2020/

## Suggested fixes
  1. change last row
  1.
  1.

**Comment by dmackie** [comment]
This was fixed by @vukosim in https://github.com/dsfsi/covid19za/commit/de8e4227b95cf5335812f087359a5733a3605580
