### ISSUE TITLE
Missing 4 Cases  13 March 2020

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#2]
As per 13 March 2020, there are supposed to be 24 confirmed cases. Missing 4.

**Comment by vukosim** [comment]
4 extra cases are from the initial group who have travelled to Italy. Still need to get the official statement from NICD or DoH. Should be after this report http://www.nicd.ac.za/third-confirmed-case-of-covid-19-in-south-africa/

**Comment by vukosim** [comment]
More information on specifics of group https://businesstech.co.za/news/government/380185/7-south-africans-from-italian-tour-group-test-positive-for-covid-19-coronavirus/

**Comment by Ofentswe1** [comment]
Are these 4 cases still outstanding at the moment? or not yet confirmed by department of health?

**Comment by vukosim** [comment]
Yes, we have traced these. Thanks.
