### ISSUE TITLE
[DATA] Date value wrong in covid19za_provincial_cumulative_timeline_confirmed.csv

### ISSUE THREAD

**Issue by 1Map** [dsfsi/covid19za#201]
## Which Dataset
covid19za_provincial_cumulative_timeline_confirmed.csv

## Error Description

You will notice in the latest csv file the mistake (In bold below)

21-04-2020 | 20200421 | 345 | 106 | 1199 | 671 | 27 | 24 | 16 | 24 | 1010 | 43 | 3465 | 
22-04-2020 | **20200421** | 377 | 106 | 1224 | 758 | 27 | 23 | 16 | 24 | 1079 | 1 | 3635 |

**Comment by dmackie** [comment]
This was fixed by @vukosim in https://github.com/dsfsi/covid19za/commit/de8e4227b95cf5335812f087359a5733a3605580
