### ISSUE TITLE
It would be worth including the lockdown level per province starting from 1 May

### ISSUE THREAD

**Issue by codeChap** [dsfsi/covid19za#216]
It would be worth including the lockdown level each province is at starting from 1 May. Been able to see how infection rates increase or decreate according what level a province is in would be a valuable insite.

Id suggest an extra column in "covid19za_provincial_cumulative_timeline_confirmed.csv" labeled level.
![photo_2020-04-27_06-58-37](https://user-images.githubusercontent.com/451621/80335464-a714a580-8854-11ea-90fd-945a2d6d7235.jpg)
![photo_2020-04-27_06-58-55](https://user-images.githubusercontent.com/451621/80335466-a8de6900-8854-11ea-8131-34c3d962c88c.jpg)
![photo_2020-04-27_06-59-00](https://user-images.githubusercontent.com/451621/80335468-a976ff80-8854-11ea-9a2d-b55686bb00d5.jpg)
![photo_2020-04-27_06-59-03](https://user-images.githubusercontent.com/451621/80335471-aa0f9600-8854-11ea-8649-3af4ed3e5a0b.jpg)
![photo_2020-04-27_06-59-07](https://user-images.githubusercontent.com/451621/80335473-aaa82c80-8854-11ea-9362-574f394cf530.jpg)
![photo_2020-04-27_06-59-10](https://user-images.githubusercontent.com/451621/80335474-aaa82c80-8854-11ea-8ed9-4aa059601bc6.jpg)

**Comment by vukosim** [comment]
Thanks @codeChap we can create the file to keep track of that. If you can assist with keeping it updated?

**Comment by codeChap** [comment]
Cool, if you create the file I’ll look after it. Or I can create it. What columns would we need  - level and source of information?

**Comment by vukosim** [comment]
See the cumulative province. 

create a folder called lockdown in the data folder and put the file in there.

**Comment by IamC8** [comment]
Hi guys. I was looking at info regarding the levels and came across your conversation.
I was looking everywhere for more info on this topic.
Saw on co.za that a new site was created: http://lockdownlevel.co.za/ but not sure if it is a hobby site or gov site. Hosted on Afrihost, so I assume hobbyist. 
Anycase, will there be an official site with the global, provincial, district, and metro levels as indicated by the president in his speech? Does anyone know?
And then secondly do we know how the different levels will affect the others?
A city at level 2 in a metro at level 4. Which overrides which?
Maybe something to think about when generating data.
Just my 2 cents

**Comment by codeChap** [comment]
Yes - it looks like it might break down beyond a provioncial level. Ethekwini could have remained on Level 5, while the rest of the provinc would have been on level 4. So the data structure is probably going to have to change.
