### ISSUE TITLE
[BUG] Dashboard showing zero cases for 26 April

### ISSUE THREAD

**Issue by bmerry** [dsfsi/covid19za#217]
**Describe the bug**

The datastudio dashboard shows 0 total cases for 26 April.

**To Reproduce**
1. Go to https://datastudio.google.com/u/0/reporting/1b60bdc7-bec7-44c9-ba29-be0e043d8534/page/hrUIB
2. Look at the graph of total positive cases.

**Expected behavior**

April 26 should have a non-zero number of cases.

**Screenshots**

![Screenshot_2020-04-27 COVID 19 ZA Dashboard](https://user-images.githubusercontent.com/1963944/80342972-640efe00-8865-11ea-846c-8a87449b5363.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 75.0

**Comment by vukosim** [comment]
Thanks @bmerry picked it up and fixed.
