### ISSUE TITLE
NEW INFECTIONS

### ISSUE THREAD

**Issue by Data-Saba** [dsfsi/covid19za#22]
## Error Description
Two-year-old case here states that it is from travelling from New Zealand yet the government and NICD statements state 2-year-old male with no international travel history. 

## Suggested fixes
  1.
  1.
  1.

**Comment by vukosim** [comment]
Which case id is that @Data-Saba?

**Comment by vukosim** [comment]
Both 2 year olds are correct. Thanks @Data-Saba closing this.
