### ISSUE TITLE
Luvenda Translation of the dashboard

### ISSUE THREAD

**Issue by rudzanimulaudzi** [dsfsi/covid19za#228]
Hello,

I'm interested to contribute to this project, I have not as yet found a way in. However, I would like to offer translations into Tshivenda / Luvenda language, similar to what was done with Xitsonga.

**Comment by vukosim** [comment]
I have asked the creator of the Xitsonga version to comment.

**Comment by vukosim** [comment]
@rudzanimulaudzi have you been able to start?

**Comment by Sneidon** [comment]
Please accept my apologies for the reply @rudzanimulaudzi  and @vukosim. It gapped my mind som how. It is important we translate this important data to all languages in SA.

The approach we took for Xitsonga was 1) get a go ahead from Dr. Vukosi. 2) find translations for all labels on https://dsfsi.github.io/covid19za-dash/. 3) Created graphs for free using Google data studio.

On going, we manually update the datasets (CSV) as the main repo is updated. There might be a better way of doing this but we were pressed for time. I am happy to assist if you need help with translations or Google

**Comment by vukosim** [comment]
@rudzanimulaudzi Can you respond.

**Comment by rudzanimulaudzi** [comment]
Hi Dr. Vukosi, for some reason I missed the response from @Sneidon. I am keen, sounds like it's just manual updates of labels then recreating graphs with data studio.

I can on Sunday and probably complete it the weekend that follows or on the 16th of June.

@vukosim are you able to send me a "copy" of the data studio site (does google allow that?) that I can update? trying to take the next steps.

**Comment by Sneidon** [comment]
@rudzanimulaudzi let me help with the data studio part. Just send a meeting request for any day, it shouldn't take 30 min to setup.

**Comment by rudzanimulaudzi** [comment]
Great, thanks @Sneidon . I got your email address.

**Comment by rudzanimulaudzi** [comment]
Thanks Dr. Vuko & Sneidon.

Will "launch" the dashboard tomorrow: https://rudzanimulaudzi.github.io/covid19/

**Comment by vukosim** [comment]
Thanks @rudzanimulaudzi and @Sneidon 

Closing this as we now have http://luvenda.com/covid/

**Comment by Sneidon** [comment]
@rudzanimulaudzi congrats and thanks @vukosim.
