### ISSUE TITLE
[Feature] Query

### ISSUE THREAD

**Issue by poshzel** [dsfsi/covid19za#229]
Hi, first thank you very much for this data set. May i ask if you can direct me to a source where i can find the following data please: Number of beds available per province, number of hospitalized patients, number of icu patients of hospitalized number, number of vent patients of icu number, list of co-morbidity per admission, age breakdown for positive tests, hospitalization, icu and vents; gender breakdown of positive tests, hospitalization, icu and vents. i would be able to help with the columns etc and basic excel formulas, but i cant find source data. please could you help or direct me? thank you very much

**Is your feature request related to a problem? Please describe.**
Lack of data to complete a dataset

**Describe the solution you'd like**
Number of beds available per province, 
number of hospitalized patients,
 number of icu patients of hospitalized number, 
number of vent patients of icu number, 
list of co-morbidity per admission, 
age breakdown for positive tests, hospitalization, icu and vents; 
gender breakdown of positive tests, hospitalization, icu and vents.

**Describe alternatives you've considered**
As above

**Additional context**

**Comment by vukosim** [comment]
@poshzel Please see the healthsystems files. And if you have any other queries you can also tag

@elolelo @anelda and @MikeMcMalace

**Comment by poshzel** [comment]
Hi Vukosim,
I think I am a bit new to this site.  I cannot seem to find the healthsystem files.  Could you possibly give me a link to them. Many thanks

**Comment by anelda** [comment]
Hi @poshzel, the health facility data is in https://github.com/dsfsi/covid19za/tree/master/data. All the hospital files have the word `hospital` in the file name. The data is described here - https://github.com/dsfsi/covid19za/blob/master/data/README_hospital_data.md and in this issue - #115 

I'm not sure where the information about hospitalisation is coming from. Much of the information you're looking for is not available from this repo or from anywhere else that is publicly available as far as I know. You might have to scrape the web and news articles/Twitter to find some of that information.

**Comment by vukosim** [comment]
Thanks @anelda
