### ISSUE TITLE
[Feature] Realtime R0 notebook automation

### ISSUE THREAD

**Issue by heerden** [dsfsi/covid19za#249]
**Is your feature request related to a problem? Please describe.**
To continue the discussion after my last pull request #227, I followed @vukosim suggestion to add a Github Action script.

**Describe the solution you'd like**
I have simulated a possible solution on my fork.

The automation is driven by the [realtime_r0_action.yaml](https://github.com/heerden/covid19za/blob/master/.github/workflows/realtime_r0_action.yaml) file.

The `Realtime R0` notebook has been updated to export the final results to `data/calc/calculated_r0_sa_provincial_cumulative.csv`.

Only when `data/covid19za_provincial_cumulative_timeline_confirmed.csv` is updated in the repo, will this action be triggered. An Ubuntu-Linux instance is then created by Github to perform the following core tasks:
1 . Check-out the latest git commits
2. Setup Python and all dependencies
3. Run the notebook, which will export the latest results to csv file
4. Only commit the results csv file back

A successful run of the script has been simulated on my [fork here](https://github.com/heerden/covid19za/runs/641009082?check_suite_focus=true).

**Describe alternatives you've considered**
The alternative is to create or extend a server to: fetch the latest results, run the Python notebook methods and store the latest results on that server. A front end dashboard cannot wait a minute for calculations to be completed every time.

Extending the current Go server will mean all the Python scripts need to be translated and I do not even know if Go's statistical libraries are that strong.

If required another Django/Python server while be recommended for this task.

**Additional context**
To ensure compliance with the rest of the repo, the following naming conventions need to be accepted or be adapted:

1. Create a new `data/calc/` folder
2. Name the exported notebook results `calculated_r0_sa_provincial_cumulative`
3. Commit the results with the message `Ro notebook action run`, example on my [fork here](https://github.com/heerden/covid19za/tree/master/data/calc).

Hope we can take this forwards?

**Comment by vukosim** [comment]
Fantastic @heerden. Can you do the pull request?

**Comment by heerden** [comment]
You can see pull request #250 

The action can be trigger by several events. Currently, it will only trigger when `covid19za_provincial_cumulative_timeline_confirmed.csv` changes, but we can also set it for changes in a specific branch or when a tag is assigned to a commit.

**Comment by heerden** [comment]
I see the action is running well.

@vukosim for the second yml you created, which notebooks do you have in mind? If there is a common trigger we can combine all the run step in one instance?

**Comment by heerden** [comment]
The notebook and Action have been updated to export district results, with pull request #266.

**Comment by heerden** [comment]
Glad to see that most regions are below 1 today!

**Comment by vukosim** [comment]
Thank you @heerden for you work on this. This will now be closed.
