### ISSUE TITLE
[Feature] Adopt Provincial Testing Sheet - Sleuthing and updating

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#251]
We need assistance with someone who can adopt to update [this file](https://github.com/dsfsi/covid19za/blob/master/data/covid19za_provincial_cumulative_timeline_testing.csv) and also look for older entries [For example from provincial reports] like the Western Cape daily updates. 

This is for total number of tests done per province.

We need to go back as much as we can and also get into a rhythm of updating this frequently as testing information comes in. 

https://github.com/dsfsi/covid19za/blob/master/data/covid19za_provincial_cumulative_timeline_testing.csv

**Comment by Tensorflow13** [comment]
This needs to be done daily?

**Comment by vukosim** [comment]
@Tensorflow13, not all data is updated daily by provinces. So it can be a scheduled update, like very 2 days.

**Comment by uelsimon** [comment]
I’ve only seen updates really from the following…and they lower they get…the less consistent

Regular:
WC
GP

Semi regular:
NW
MP

Rare:
KZN

Never:
EC
FS
LP
NC

**Comment by vukosim** [comment]
Thanks @uelsimon can you update those that have been regular and semi regular for the last 2 weeks or so?

**Comment by uelsimon** [comment]
May not be able to commit to updating the CSVs…. But how about this instead (as my contribution).

I already do the scour and dump in my own spreadsheet. Anyone from the team is welcome to grab it for there. I’ve been doing a pretty comprehensive scour for a few weeks, so what I have..should be pretty accurate.

Only use what’s on the Master Data tab https://docs.google.com/spreadsheets/d/1Pyt2nfOpH0KPB5LOxeYHkYbKA7F9cRPpapyfWGIUowE/edit?usp=sharing

€

**Comment by vukosim** [comment]
@uelsimon that is fine. If we can extract data from your sheet for the csvs and you can upload them here [for what you have] I can then commit them to improve the starting data. Let us know what other data you have and where we should put it. 

The good thing about your doing the csv pull request yourself is it is recorded in github contributors.

**Comment by uelsimon** [comment]
Fair enough…. Lemme find a YouTube video for a refresher on the easiest way to do that lol…and I’ll jump in later on the live updates

As for the data I have, I’ve captured literally any stat that has been uttered from an official public source. ( think I started around mid march). The best source for consolidated data is twitter (speed and content). I’ve created this list as my jump-off point and I check it nightly, when most folks have updated their info for the day. https://twitter.com/i/lists/1251424430900871168

I record my data based on the press release date…and not the data date. ( what they say on may 4th, is recorded in my data on may 4th….even though they are reporting on the numbers for may 3rd as of midnight)

But I’ve intentionally kept everything on the one sheet, so I can get an overview of what is happening across the board. Zooming out, you will get a sense of the inconsistency in reporting…particularly at the province level…. But I don't know if its a capacity issue..or capability issue. And haven't reached out to find out if thats something they can use help with. (I haven't retroactively searched to fill initial gaps….but those Ive checked only started reporting late… like GP when they came back into session. KZN’s reporting is SMH for the level of cases they are dealing with.

€

**Comment by vukosim** [comment]
We have a guide on pull requests here https://opensource.com/article/19/7/create-pull-request-github

You can also just create sheet pages on your google sheets and just ask me to review before you convert them to csv.

**Comment by dmackie** [comment]
> We need assistance with someone who can adopt to update [this file](https://github.com/dsfsi/covid19za/blob/master/data/covid19za_provincial_cumulative_timeline_testing.csv) and also look for older entries [For example from provincial reports] like the Western Cape daily updates.
> 
> This is for total number of tests done per province.
> 
> We need to go back as much as we can and also get into a rhythm of updating this frequently as testing information comes in.
> 
> https://github.com/dsfsi/covid19za/blob/master/data/covid19za_provincial_cumulative_timeline_testing.csv

I have have gone through all the Coronavirus Press Releases from the Western Cape Gov and extracted the data they provided into a Google Sheet.  I have added a infered date column as they have said they report at 5pm (now 1pm) the previous days numbers. 

I have copied the data to a Google Sheet at https://docs.google.com/spreadsheets/d/17Jzxi_ejt5nO10TIQK3qXyIiNBsjCfYXJ8t7OY6G2RU/edit?usp=sharing

@vukosim I am happy to extract the WC Testing data and add it to the testing file.

**Comment by vukosim** [comment]
@uelsimon Are you able to share your sheet.

**Comment by uelsimon** [comment]
https://docs.google.com/spreadsheets/d/1Pyt2nfOpH0KPB5LOxeYHkYbKA7F9cRPpapyfWGIUowE/edit?usp=sharing

I am slowly working my way to being able to directly make edits.  Downloaded GitHub desktop and cloned the repo.  But mostly challenged on time.

All my data is on the Master Data Sheet, derivatives and remixes are on other sheets…so I’d recommend just focusing on the Master Data Tab for what is needed.

**Comment by shaze** [comment]
For testing data the NICD epidemiological briefs give comprehensive testing information at provincial level. eg.  https://www.nicd.ac.za/wp-content/uploads/2020/05/NICD-Weekly-Epidemiological-Brief_-Week-ending-09-May-2020-002-00000002-1.pdf   There only 3 briefs so far but hopefully they will be weekly.

**Comment by vukosim** [comment]
Thanks @shaze we are keeping track of that. Just need some time or a volunteer to extract all that data.

**Comment by shaze** [comment]
@vukosim Am happy to do this though it will take me about a week to catch up The NICD reports give number of tests per capita in each province based on Stats SA 2019 mid-year estimates. But I see people here are working on this too and I don't want do duplicate it. While the NICD reports are only weekly and seem to come out a few days later I would recommend them as being highly reliable compared to trying to get from a whole miscellany of different sources.

**Comment by uelsimon** [comment]
Agreed, I just reviewed the provincial provided versions of tests...and the numbers are definitely not aligned. But this is to be expected as the NICD numbers and province numbers have never fully aligned.  So it is prolly best to limit this document to NICD periodic updates.

**Comment by shaze** [comment]
Let me know if you want me to do this.

**Comment by uelsimon** [comment]
Please do @shaze.  Thanks in advance

**Comment by shaze** [comment]
I have been doing this but there seems to be a duplication between this
https://github.com/dsfsi/covid19za/blob/master/data/district_data/provincial_testing_data.csv

and 

https://github.com/dsfsi/covid19za/blob/master/data/covid19za_provincial_cumulative_timeline_testing.csv

There seems to be duplication between what I am doing and what @lrossouw is doing. We should only have one. Some overlaps between data is useful (for example, I have added cases to my tests file because the dates on which the difference department releases information is different and it's useful to be able to cross-reference) but these files are doing the same things. I am happy to step back with this if @lrossouw wants to run with it.

**Comment by lrossouw** [comment]
I had not seen the provincial table in the district folder.  I also think there are provincial data released sporadically by each province vs. provinical data release by NICD on (possibly) on a weekly basis.

I had not committed to updating it but did commit some numbers when I saw them.  I would say the right place for data released nationally for provinces would be `data/covid19za_provincial_cumulative_timeline_testing.csv`.  All other provincial data sits in that path. It would not make sense to make logical sense to put provincial data in a district folder but I don't know the folder hierarchy.  

I though I might use it for a model I was building but not sure if I will. 

I would try to update where I can.  Happy to take guidance from maintainer as to where what should be though :)

**Comment by shaze** [comment]
Agreed-- I think  @vukosim should make a call here.

I think we should avoid ad hoc release of data by individual provinces because it makes it very hard to compare across provinces (or rather if there is there is a province that releases this daily then there should be a separate file for it). And I think we should avoid secondary sources using only official resources like NICD or one of the departments of health.

**Comment by shaze** [comment]
@vukosim @lrossouw @SimonRosen173  I agree with @lrossouw  We don't want to duplicate work and I don't think we should have the same data in two different places as it is confusing and hard to maintain. Unless there are objections, I suggest to delete `https://github.com/dsfsi/covid19za/blob/master/data/district_data/provincial_testing_data.csv` and   that we should adopt `covid19za_provincial_cumulative_timeline_testing.csv` as the source for testing data.
