### ISSUE TITLE
[Feature] Add Negative Cases 

### ISSUE THREAD

**Issue by mtswenij** [dsfsi/covid19za#26]
**Negative Cases**
It would also be useful to add negative cases in the dashboard

**Comment by vukosim** [comment]
Hmm, we have the total tests which should mean most are negative.

**Comment by mtswenij** [comment]
> Hmm, we have the total tests which should mean most are negative.

Sure, I understood the positive minus tested would show work, but may be nice to have it like in the doh website

**Comment by vukosim** [comment]
Will look at the best way to put it up. Thanks @mtswenij

**Comment by anelda** [comment]
I was looking into that as part of #17. Have written the code but getting stuck with the visualisation. Also had a load of questions about the data. Will share code later today.

**Comment by elolelo** [comment]
@vukosim have you looked at the best way to present @mtswenij 's suggestion?
Hi @anelda did you  manage to find answers to the questions on the data? Are you still to share the data viz?

**Comment by anelda** [comment]
@elolelo thanks for bringing this up again. My opinion is that we simply don't have enough information about negative cases to say more than that there were X number of negative cases based on the positive tests vs number of tests. It can be people who were cured, or people with false negatives who may or may not have tested positive later. Can't think that there's currently justification for negative cases on a plot. What do others think?

**Comment by elolelo** [comment]
@anelda Thanks, your opinion is telling enough to close this for now and we can reopen it later when we have enough info.
