### ISSUE TITLE
[BUG] Wrong captions for WC reproduction rate

### ISSUE THREAD

**Issue by nvddussen** [dsfsi/covid19za#287]
https://datastudio.google.com/u/0/reporting/1b60bdc7-bec7-44c9-ba29-be0e043d8534/page/MX5LB

The realtime reproduction rate graph for the western cape is captioned as Gauteng.

**Comment by vukosim** [comment]
Fixed @nvddussen Thank you.

**Comment by nvddussen** [comment]
Great!

You guys are wonderful!  Amazed what you did with minimal info!

Regards
Nico
