### ISSUE TITLE
[IDEA] Split the transmission type By Gender and Age

### ISSUE THREAD

**Issue by DataDroidKay** [dsfsi/covid19za#29]
**Is your feature request related to a problem? Please describe.**
This is just an idea.

**Describe the solution you'd like**
Would be insteresting to see the transmission type by gender and age

**Describe alternatives you've considered**

**Additional context**

**Comment by elolelo** [comment]
@DataDroidKay It would be interesting but right now we are still looking for help with validating the data that we already have with the data that is reported by the DoH. Now I will keep note of  this  idea and  reopen it when validation is done.
