### ISSUE TITLE
[BUG] Action workflow need for updated realtime notebook

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#292]
Hey @heerden, please check the notebook for a regression that causes the workflow to fail for realtime rt.

**Comment by heerden** [comment]
Hi @vukosim, it was the low variability in the NW district data which caused the error. I have removed those districts for now. Here is the pull request #294 

I will work on some additional error handling to avoid future bugs like this.

**Comment by vukosim** [comment]
Thanks @heerden
