### ISSUE TITLE
Need volunteers to create line list for COVID19 cases in Africa

### ISSUE THREAD

**Issue by ensoesie** [dsfsi/covid19za#32]
We want to build what is called a line list – a table summarizing information about people who are infected, dead, recovered etc. The table would include demographic and location information. Such a dataset would help us understand how COVID19 transmission in Africa is similar or different to what’s being observed in other regions of the world.

This would be part of a broader effort focused on collating COVID19 data globally. We need volunteers ASAP to help in this effort. The data will be made publicly available and volunteers will be acknowledged. 

onelaine@bu.edu

**Comment by vukosim** [comment]
This will be moving to https://github.com/dsfsi/covid19africa
