### ISSUE TITLE
[DATA] Wrong/missing keys in district_gp_keys.csv

### ISSUE THREAD

**Issue by Strasheim88** [dsfsi/covid19za#327]
## Which Dataset
district_gp_keys.csv

## Error Description
1. Keys of Tswhane districts on gp_tshwane.csv (e.g. Tshwane 2) do not match with district_gp_keys.csv (e.g. City of Tshwane 2).
2. Ekurhuleni keys: missing key for Ekurhuleni Unallocated, and Ekurhuleni East 1 duplicated.
3. JhbG missing in keys.

## Suggested fixes
  1. Change keys to coincide with gp_tshwane.csv
  1. Add Ekurhuleni Unallocated key and value, and fix Ekurhuleni East 2 key.
  1. Add JhbG key and values.

**Comment by vukosim** [comment]
Thanks. @shaze could you respond.

**Comment by shaze** [comment]
Thanks for the fixes. Will fix all except removing "unallocated" from keys file as this is not a district. Happy to discuss. Please review and let me know if I missed anything or if you see anything new.

**Comment by Strasheim88** [comment]
Thank you. I would argue for including "unallocated" in keys, because in all three of the Gauteng district datasets (Johannesburg, Tshwane, Ekurhuleni) there are the 'placeholder' sub-districts for unallocated cases. If one wants to use this key file  to define the names/places for the relevant sub-district keys found in the datasets, there will be no sub-district key or value for the 'unallocated' cases?

PS. thank you for your work on this, this is tremendously helpful and useful data!

**Comment by shaze** [comment]
I've updated in my pull request -- as soon as accepted you should see it. Let me know if OK now.  Yes, there are no key values. Also no key values for Sedibeng and West Rand local municipalities.

**Comment by Strasheim88** [comment]
Thanks. Can you include a name or description of some sort in the value field for the unknown (e.g. 'Ekurhuleni Unknown'), Sedibeng and West Rand keys? This would coincide with the practice on the Western Cape's keys for the unknown key (https://github.com/dsfsi/covid19za/blob/master/data/district_data/district_wc_keys.csv). I am using these lists as a form of Master Data for the keys to retrieve the places/descriptions, if that makes sense. 

Unless you are using it for something else.

**Comment by shaze** [comment]
Please have a look at https://github.com/shaze/covid19za/blob/master/data/district_data/district_gp_keys.csv 
before I do a pull request

**Comment by Strasheim88** [comment]
Thank you. One last thing, could you add the name of the relevant district next to 'unknown' in the description, e.g. 'Ekurhuleni Unknown'. Otherwise there is no way of knowing which 'Unknown' you are looking at when only using the value.

**Comment by Strasheim88** [comment]
Seems perfect now, thanks @shaze.
