### ISSUE TITLE
patient-level comorbidity data please!!

### ISSUE THREAD

**Issue by jphfisher** [dsfsi/covid19za#33]
Hi,

I'm a paediatrician working in the UK.  We need data on the pre-existing medical conditions of children who catch COVID, so that we can start looking for patterns.

When you're collecting your data, please please include individual patient data on people with co-morbidities, especially children but I figure it would be useful for adults too!  We'd need their ages as well ;)

I'm happy to be contacted on the email in my profile, and then we can move over to my official NHS account if needs be.

All the best

Dr Jonathan Fisher
NIHR Clinical Lecturer in Paediatrics
UCL-GOS Institute of Child Health

**Comment by vukosim** [comment]
Unfortunately, we do not have that available yet being published by [NICD](nicd.ac.za)

**Comment by brucellino** [comment]
@vukosim would it be possible to liase with NICD to request that this be part of their patient intake questionnaire?

**Comment by elolelo** [comment]
@vukosim Have you considered what @brucellino commented on? What is the status?

**Comment by vukosim** [comment]
@jphfisher please take a look at the death data we collated https://github.com/dsfsi/covid19za/blob/master/data/covid19za_timeline_deaths.csv
