### ISSUE TITLE
[DATA] Cumulative deaths incorrect

### ISSUE THREAD

**Issue by shaunsaker** [dsfsi/covid19za#334]
## Which Dataset

https://raw.githubusercontent.com/dsfsi/covid19za/master/data/covid19za_timeline_testing.csv

## Error Description

The [latest article on sacoronavirus.co.za](https://sacoronavirus.co.za/2020/05/19/update-on-covid-19-19th-may-2020/) states that the cumulative deaths is 312 while the above dataset has a figure of 372. 

## Suggested fixes
  1. Change cumulative deaths in the above dataset to 312.

**Comment by vukosim** [comment]
Thank you. Fixed
