### ISSUE TITLE
[Feature] district_lp_keys.csv - Link between municipality key and district key

### ISSUE THREAD

**Issue by Strasheim88** [dsfsi/covid19za#368]
**Is your feature request related to a problem? Please describe.**
Currently, there are two region levels in this key file, namely district keys (e.g. DC33 - Mopani) and own level lower, namely municipality keys (e.g. LIM334 - Ba-Phalaborwa). There is no link between the two levels, which makes it difficult to roll up or drill down.

**Describe the solution you'd like**
- Add a field that defines what level the key falls under, e.g. "District" or "Municipality".
- Add a field that defines the "parent" district per municipality, e.g. DC33 for LIM334.

**Describe alternatives you've considered**
None.

**Additional context**
N/A

**Comment by JosephSefara** [comment]
Familiarise yourself with official [MDB](http://www.demarcation.org.za/site/) naming. The mapping between province to district to municipality to ward can be found from the MDB. Luckily see this [file](https://github.com/dsfsi/covid19za/blob/master/data/district_data/LM_2018.csv) for mappings. Column CAT_B is a municipality and column DISTRICT is a district.
To answer your 1st feature
- _Add a field that defines what level the key falls under, e.g. "District" or "Municipality"._
When a code belongs to **CAT_B** is a municipality and **DISTRICT** is a district.

To answer  your 2nd feature:
- _Add a field that defines the "parent" district per municipality, e.g. DC33 for LIM334._
We know municipality is a **subdistrict** so values in **DISTRICT** are parent to *CAT_B* column.

NB: **district_lp_keys.csv** is used to map the column naming used in the [provincial_lp_cumulative.csv](https://github.com/dsfsi/covid19za/blob/master/data/district_data/provincial_lp_cumulative.csv). 

The link between municipality key and district key can be derived from [LM_2018.csv](https://github.com/dsfsi/covid19za/blob/master/data/district_data/LM_2018.csv). 

Is it not important to replicate [LM_2018.csv](https://github.com/dsfsi/covid19za/blob/master/data/district_data/LM_2018.csv) for each province.

**Comment by Strasheim88** [comment]
Perfect, thank you! Thanks for pointing that out.
