### ISSUE TITLE
[DATA] Date error on provincial_nw_cumulative.csv

### ISSUE THREAD

**Issue by Strasheim88** [dsfsi/covid19za#369]
## Which Dataset
covid19za/data/district_data/provincial_nw_cumulative.csv

## Error Description
12 May 2020 is duplicated. 

## Suggested fixes
  1. Put in correct date in first instance.

**Comment by akbarganey** [comment]
How can I assist? I am new here

**Comment by vukosim** [comment]
@akbarganey You can look at files that might be stale and work to update them. Note the main README.md. If you have any problems, let me know.
