### ISSUE TITLE
[DATA] Date error in covid19za_provincial_cumulative_timeline_testing.csv

### ISSUE THREAD

**Issue by richardyoung00** [dsfsi/covid19za#373]
## Which Dataset
covid19za_provincial_cumulative_timeline_testing.csv

## Error Description
YYYMMDD column is incorrect for date 09-05-2020. The month and day are swapped around.

## Suggested fixes
change 20200905 to 20200509

**Comment by vukosim** [comment]
Thank you. Fiexed
