### ISSUE TITLE
[Feature] Add positive cases as a % of cumulative tests and % of SA population

### ISSUE THREAD

**Issue by devontighe** [dsfsi/covid19za#38]
The number of confirmed positive cases is a function of how many tests have been done.  In order to understand the extent of Covid-19's penetration, we need to know # of positive cases and # of people that have been tested relative to the total population, which is currently estimated as 59M (https://www.worldometers.info/world-population/south-africa-population/)

**Comment by anelda** [comment]
@devontighe do you have an example of plot that you'd like to see? We've been trying to do that (also showing negative tests). Please see comments at #17. I'm a bit stuck with coming up with a good plot that will tell a story.

**Comment by devontighe** [comment]
@anelda I've responded in comment #17 . Maybe something like this could work? (or hold off on including % recovered to start as that % recovered would overlap with % negative)

![SA_Covid19_chart](https://user-images.githubusercontent.com/25172032/77152867-71d0a700-6aa1-11ea-8add-4688664a415f.jpeg)
