### ISSUE TITLE
Missing data for 2020-05-28 in covid19za_provincial_cumulative_timeline_recoveries.csv

### ISSUE THREAD

**Issue by andrealouw** [dsfsi/covid19za#382]
The data is available in [tweet](https://twitter.com/COVID_19_ZA/status/1266131226135597057/photo/2)

**Comment by chadwpetersen** [comment]
Let me provide a PR for this @vukosim.

**Comment by chadwpetersen** [comment]
@vukosim -> this updates the recoveries data #384.
