### ISSUE TITLE
Different Dates format

### ISSUE THREAD

**Issue by Ofentswe1** [dsfsi/covid19za#4]
Hi @vukosim, can you make all the date format to be the same, you are using two different format, you are using  YYYY-MM-DD and YYYY-DD-MM on the same column, I have explored the data and I have spotted that.

**Comment by vukosim** [comment]
Hey @Ofentswe1 the date formats are the same, unless I cant see.

**Comment by Ofentswe1** [comment]
I will fix the dates in the CSV and push shortly

**Comment by Ofentswe1** [comment]
> Hey @Ofentswe1 the date formats are the same, unless I cant see.

Oh I see, Its pandas on my site it picks up the wrong date formats but I have fixed it, I will push after the changes

**Comment by vukosim** [comment]
Maybe you can add also a column in a standard date time like YYYYMMDD?
