### ISSUE TITLE
[Feature] Custom Domain for Dashboard

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#41]
Investigate getting a custom domain for the dashboard that is easy

maybe https://coronavirusza.co.za

**Comment by anelda** [comment]
Be careful not to cause confusion with http://sacoronavirus.co.za/ the official DoH site. How about https://coronavirus-dashboard.co.za or something to that effect?

**Comment by vukosim** [comment]
Great point.

**Comment by huntingphi** [comment]
I've got coronavirusinfo.co.za parked, you're free to use it if you want

**Comment by elolelo** [comment]
@vukosim  and  @anelda  What are your thoughts on using the offered parked domain name? 
Thanks @huntingphi for the offer

**Comment by anelda** [comment]
@elolelo don't think it's my decision to make :-)

**Comment by huntingphi** [comment]
No prob, just @me if you guys are settled on using it
