### ISSUE TITLE
[Feature] No of recoveries on Dashboard

### ISSUE THREAD

**Issue by mlsmith002** [dsfsi/covid19za#42]
**Is your feature request related to a problem? Please describe.**
Not relating to an issue, just an idea.

**Describe the solution you'd like**
Overlay the number of infections with the number of recoveries. 

**Describe alternatives you've considered**

**Additional context**
Currently the DB indicates that the mortality rate in SA is 0. I am concerned that people will read it in context of the number of infections (not the number of closed cases). Providing the number of recoveries will provide more context and give viewers an idea of the reliability of the proposed mortality rate.

**Comment by elolelo** [comment]
@mlsmith002  Can you be able to start by  with creating  a csv file  and populate it with headings: 
case_id | recovery date (YYYYMMDD)| province | age | gender | 
and values for all those that have recovered? 
I am not sure which  reliable Source reports on this

**Comment by elolelo** [comment]
@mlsmith002 This issue seems to be addressed in #57
