### ISSUE TITLE
[BUG][DATA] Tests dates error

### ISSUE THREAD

**Issue by anelda** [dsfsi/covid19za#43]
**Describe the bug**
The column `YYYYMMDD` and `date` in `covid19za_timeline_testing.csv` does not agree in all cases. See e.g.  
`
07-03-2020 | 20200306
`
I'm not sure what the significance of the two columns are?
Don't see the same problem in `covid19za_timeline_confirmed.csv`

**To Reproduce**
Go to https://github.com/dsfsi/covid19za/blob/master/data/covid19za_timeline_testing.csv

**Comment by vukosim** [comment]
Thank you fixed. It can impact downstream data products.
