### ISSUE TITLE
[Other Dashboards] List of dashboards from rest of world and SA

### ISSUE THREAD

**Issue by anelda** [dsfsi/covid19za#44]
I came across this list https://github.com/CSSEGISandData/COVID-19/issues/576.

Wanted to see what others are doing and how they are displaying various pieces of information. Maybe useful resource if people want to get ideas for displaying data. Most look more or less the same at this stage.

Nobody else displays information about # of tests or # negative cases (see #17, #26, #38) yet

**Comment by anelda** [comment]
https://mediahack.co.za/datastories/coronavirus/dashboard/ by Media Hack Collective - media house specialising in data journalism (source - https://www.itweb.co.za/content/wbrpO7gYb9lqDLZn)

**Comment by vukosim** [comment]
Thanks. Will likely create a folder to keep a list of those and screenshots.
