### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by D1ng3r** [dsfsi/covid19za#458]
**Describe the bug**
The total daily positive cases and daily positive cases are the graph y=0 and x=0

**To Reproduce**
![coviderror](https://user-images.githubusercontent.com/4225972/84738541-614da100-afaa-11ea-8dd3-cdff023f333d.png)

open the website and look at the variable / graph description above

**Expected behavior**
dyamic graph showing values of total positive cases in general and by province.

**Desktop (please complete the following information):**
Windows 10
Chrome
 83.0.4103.106 (Official Build) (64-bit)

**Comment by vukosim** [comment]
Thanks @D1ng3r some formatting issue on the ingestion engine.
