### ISSUE TITLE
Mpumalanga district data not updating on dashboard[BUG]

### ISSUE THREAD

**Issue by lizelgreyling** [dsfsi/covid19za#490]
Despite the Mpumalanga district data being updated every day on https://github.com/dsfsi/covid19za/blob/master/data/district_data/provincial_mp_cumulative.csv, the dashboard graphs (https://datastudio.google.com/u/0/reporting/1b60bdc7-bec7-44c9-ba29-be0e043d8534/page/pCPSB) only show Mpumalanga district data up to 14 June. Is there a problem in the district data file that I can fix to allow the updated data to be reflected in the graphs? 

There are days when the provincial heath department does not give updates, in which case I only update the totals from NICD and mark the row as such. Could this be what is breaking the update? 

Screenshot:
![image](https://user-images.githubusercontent.com/8544071/85715181-75507b80-b6eb-11ea-8418-ca785e8689bf.png)

**Comment by vukosim** [comment]
Looking into it @lizelgreyling

**Comment by vukosim** [comment]
Take a look @lizelgreyling was an issue with Google Sheets.

**Comment by lizelgreyling** [comment]
@vukosim Great, thanks!
