### ISSUE TITLE
provincial_wc_cumulative [BUG]

### ISSUE THREAD

**Issue by mdwynn** [dsfsi/covid19za#497]
## Which Dataset
covid19za/data/district_data/provincial_wc_cumulative.csv

## Error Description
The data has not updated since 19 June 2020, despite there still being an "Update on the coronavirus by Premier Alan Winde" released daily.

## Suggested fixes
  1. Unsure, as the format of the updates appears to be the same.
  1.
  1.

**Comment by dmackie** [comment]
@vukosim and @naturofix: I have code that scrapes the WC update pages and can give me back a line to add to the file.  I am willing to update this file tonight if you want?

**Comment by vukosim** [comment]
@dmackie Thanks for that. That may allow us to automate then nightly. @naturofix are you okay with that? So if you make it a script that we can use that.

**Comment by dmackie** [comment]
@vukosim and @naturofix: The script has to be given the URL of the page to get the data from so it's not something that can be scripted currently as it cannot find the correct page to fetch.  When I upload the code I will let you y'all know.
