### ISSUE TITLE
[Feature] Issues by region in a district

### ISSUE THREAD

**Issue by ntobekoMkhize** [dsfsi/covid19za#50]
**Is your feature request related to a problem? Please describe.**
Currently the dashboard does not allow the user to drill down and explore the cased within their immediate locality (region/district)

**Describe the solution you'd like**
There could be an additional field in the confirmed_cases model to represent the region in which the case was detected.

**Describe alternatives you've considered**
None

**Additional context**
I've noted that the City of Joburg is now publishing this data.

**Comment by vukosim** [comment]
Can you provide the city of Johannesburg example

**Comment by ntobekoMkhize** [comment]
> Can you provide the city of Johannesburg example

I only have the attached PDF sent via WhatsApp, I'm still trying to determine where it was originally published.

![Image](https://user-images.githubusercontent.com/12089287/77190036-30f88280-6ae1-11ea-91fe-3b9844b145db.jpeg)

**Comment by vukosim** [comment]
Yeah we need to know where we can find the original source.

**Comment by elolelo** [comment]
@ntobekoMkhize how did it go with finding the source?

**Comment by ntobekoMkhize** [comment]
@elolelo I didn't manage to find the source as yet.

**Comment by elolelo** [comment]
@ntobekoMkhize Ok , thanks for the update - I will open this again when we find the source.
