### ISSUE TITLE
[DATA] FS last entry is a FEMALE not a MALE

### ISSUE THREAD

**Issue by quincy111** [dsfsi/covid19za#51]
## Which Dataset
covid19za_timeline_confirmed.csv

## Error Description
The 32 year old FEMALE was incorrectly made a MALE in the PDF.  In the raw data she is a FEMALE.  Blame the GOV.

## Suggested fixes
  1.  Change the last Free State Entry for 20032020 to a FEMALE
  1.
  1.

**Comment by vukosim** [comment]
Thanks. Is this a discrepancy across statements. Can you upload the incorrect and correct one?

**Comment by vukosim** [comment]
Thanks @quincy111, NICD released updated PDFs now so using that, will close this.

**Comment by vukosim** [comment]
https://sacoronavirus.co.za/wp-content/uploads/2020/03/Latest-confirmed-cases-21-March-.pdf.pdf.pdf
