### ISSUE TITLE
[Feature] Mapping Hospitals

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#53]
**Describe the solution you'd like**
We now have hospital data available, it will be updated in the next few days. We need to map all of the hospitals. On hover, there must be some information on the district size, bed capacity etc.

**Comment by vukosim** [comment]
Hey @BolelangHS

**Comment by JayWelsh** [comment]
Hi @vukosim , I have written the code to map the hospitals but it seems that we currently lack location data for hospitals in the Western Cape, here is a preview from my localhost:

<img width="885" alt="Screenshot 2020-03-22 at 14 31 23" src="https://user-images.githubusercontent.com/14224459/77249519-3de4b580-6c4a-11ea-8b82-ed7fa4d7f47c.png">

**Comment by vukosim** [comment]
That's fine. We'll be updating soon with that. Is the hover information per hospital. Is it possible to also have a hovering table with a list of all the hospitals?

**Comment by lainglo** [comment]
hi guys, not sure if you are aware of these tools / sites:

https://healthsites.io/map
https://www.healthestablishments.org.za/Home/Facility

**Comment by MikeMcMalace** [comment]
Hey, aware yes. The problem with these are that they do not specify capacity and district information. 

Currently, you can get data like this (see below) from the National data dictionary. 
Health Patient Registration System implemented	Yes
Health Patient Registration System registered patients as at 16/03/2020	3157
Ideal Clinic score	59
Ideal Clinic category	Not achieved
Ward Based Outreach Team linked	No
Number of Ward Based Outreach teams linked	None
Register pregnant women on MomConnect	Yes
Linked to Centralised Chronic Medicines Dispensing and Distribution points	No

The data we need are all of these, plus information about the districts, plus information surrounding if the hospital can handle COVID-19 patients. Currently, we have less than 15 hospitals allocated for COVID-19, but as time continues, we need to be able to update this. Furthermore, as you can see from the links you shared @lainglo , there still exists a lot of incomplete data. 

Part of the idea is to collect and display (just like above in the links provided) with complete information, in a way that is useful.

**Comment by lainglo** [comment]
Thanks @MikeMcMalace . I am currently working on a Master Facility List web application for DoH. Just want to make sure we are all coordinating and not duplicating any efforts. We are pushing to go live asap, will let you know any details.

Glad to help.

**Comment by ksharpeypd** [comment]
If helpful, here's the westerncape hospitals attached in .csv

sourced from: http://snisnet.net/MFLDSS/MFLDSS.php?source=4&country=ZA&factype=0&owner=0&snu=521

[WC_Hospitals.csv.zip](https://github.com/dsfsi/covid19za/files/4370368/WC_Hospitals.csv.zip)

**Comment by vukosim** [comment]
@elolelo Is it possible to get a flourish dashboard done with the updated hospital data?

**Comment by elolelo** [comment]
@vukosim Yes, its possible and I have some time to work on it with others.

**Comment by elolelo** [comment]
@ksharpeypd  Thanks for the data , see #117 on how to give more detailed credit for it.  If you have  more data  on hospitals  for contributions -  please see this #115 . For now, we will review what you have shared with what @MikeMcMalace @altadewaal @vukosim  and others have shared. Thanks!

@lainglo ,Thanks for those links, I have just looked at them and I second @MikeMcMalace with the incompleteness of data amongst other minor things. You may check out this issue  #115  on what type of data  we are currently working on. If you have data that you can contribute - issue #117 addresses how you should go about this.
