### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [dsfsi/covid19za#542]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/6PBQY0
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by vukosim** [comment]
@reeshmabijosh Please remove the data as we already have the data on Zenodo, unless you replace the DOI with the Zenodo.

Zenodo https://zenodo.org/record/3938381

**Comment by vukosim** [comment]
Please remove the same from the covid19africa data. Both READMEs explain that the data is already in an archive.

**Comment by vukosim** [comment]
@reeshmabijosh Can you please respond and update

**Comment by reeshmabijosh** [comment]
Hello Vukosi,
Sorry for the late reply.
Can you please contact  goncharova.kira@gmail.com. I do not have permission
to update the dataset.

Thank You
Reeshma.K

**Comment by vukosim** [comment]
@reeshmabijosh I had used the contact on the website and still, never got a response.

2nd it is clearly described on both repos how they are archived and please resolve it.
