### ISSUE TITLE
[Feature] Adopt Northern Cape District Sheet

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#561]
We need some help filling in and keeping up with NC district numbers.

This is creating and adopting the file https://github.com/dsfsi/covid19za/blob/master/data/district_data/provincial_nc_cumulative.csv

See this folder for the other provinces https://github.com/dsfsi/covid19za/tree/master/data/district_data and how you can create the file for NC

You can use the NC Health twitter account for source of historical data https://twitter.com/nc_doh/

**Comment by richardyoung00** [comment]
The NC data should also include a YYYYMMDD column to be consistent with the other files.

**Comment by vukosim** [comment]
@richardyoung00 yes.

**Comment by danievanmopanie** [comment]
Hi @vukosim,

Glad to volunteer!  I am a resident of the Tsantsabane LM (Postmasburg).

**Comment by vukosim** [comment]
Thanks @danievanmopanie, please do add that extra column.

**Comment by danievanmopanie** [comment]
Can we close this issue?
