### ISSUE TITLE
[DATA] Data for Bojanala district and Dr Kenneth Kaunda district in North West is swapped around

### ISSUE THREAD

**Issue by h-ndre** [dsfsi/covid19za#573]
## Which Dataset

https://github.com/dsfsi/covid19za/blob/master/data/district_data/provincial_nw_cumulative.csv

## Error Description
The number of cases for Bojanala district and Dr Kenneth Kaunda in North West is swapped around.

https://twitter.com/NorthWestDOH/status/1284388516902862850/photo/1

## Suggested fixes
  1. Swap headings
  1. Swap data
  1.

**Comment by vukosim** [comment]
Fixed @h-khoza 
Please check and close if satisfied
