### ISSUE TITLE
[DATA] WC and KZN data may be incorrect

### ISSUE THREAD

**Issue by NoorMosia** [dsfsi/covid19za#58]
## Error Description
according to news24 and timeslive the numbers are 27 and 74 not 26 and 75 respectively.

**Comment by vukosim** [comment]
Thank you. We will investigate.

**Comment by elolelo** [comment]
@vukosim Have you started with the investigation? Where are you (progress level) on this is issue?

**Comment by vukosim** [comment]
At the moment it seems some error that was fixed on NICD side, but have not been able to figure out which patient has to be swaped between KZN and WC. So for the moment, we leave this error of 1 discrepancy @elolelo
