### ISSUE TITLE
[DATA] Western Cape total cases on 2020-07-19 has been updated. 

### ISSUE THREAD

**Issue by andrealouw** [dsfsi/covid19za#583]
## Which Dataset
https://github.com/dsfsi/covid19za/blob/master/data/covid19za_provincial_cumulative_timeline_confirmed.csv

## Error Description
Western Cape data is incorrect for 2020-07-19.
The cumulative cases seem to decrease between the 19th and the 20th of July.

## Suggested fixes
Link to updated Western Cape figures for 2020-07-19, along with the data error explanation. 
https://coronavirus.westerncape.gov.za/news/update-coronavirus-premier-alan-winde-19-july

**Comment by lrossouw** [comment]
Yeah I noticed the issue last night, but wasn't sure how to correct.  I can spread the correction over the last week as an approximation because Winde indicates that:

>The total number of cases in the Western Cape is lower today than it was yesterday. This is because some cases from other provinces were mistakenly allocated to the Western Cape over the past week. This has been corrected, and as such, the total number of cases stands at 83 948 today.

So the correction needs to be spread over 7 days to 20 Jun is my interpretation?  Thoughts?

**Comment by horscroft-swish** [comment]
Is it possible to annotate data points with unique info? Maybe spreading the correction retroactively isn't the right goal if a note can be added on the downwards data point indicating the issue.

**Comment by lrossouw** [comment]
There is space for a link at the end of the line.  Last time we noted issues there was a note in Dr. Mkhize's press release, and that link was added to the line.  So I went looking for it before capturing 20 Jul 2020, but there was no note.  I have generally assumed that we just capture the data as is effectively.  So we can correct the by deducting the numbers somehow, but it will be a guess as to what it is.  It will require an assumption.  It's clearly not just 19 Jul that's wrong though.  I can add the link from Winde and just leave the data as is?

**Comment by andrealouw** [comment]
https://coronavirus.westerncape.gov.za/covid-19-dashboard
One could maybe use the date slider to update the cases for the WC.
But his would be a pain to maintain if the these continue to differ from the national report.

**Comment by lrossouw** [comment]
Not sure if that would be correct, because the data we have to date is by date reported by Dept. of Health/NICD.  The data in the dashboard is by date of test I believe?  So you would see the most recent dates also has only a few cases.

**Comment by lrossouw** [comment]
I think I'm leaning towards option 2.  Agreed?

**Comment by vukosim** [comment]
LGTM @lrossouw
