### ISSUE TITLE
[Possible data error] Cumulative graphs for WC have decreased 19th->20th July

### ISSUE THREAD

**Issue by horscroft-swish** [dsfsi/covid19za#584]
In the WC dashboard, the latest tick of data has seen a decrease in the WC numbers (Jul 19: 85,926 to Jul 20: 85,772). The "total cases" value remains at  85,926. 

Is this a known error in the data/previously reported numbers? Or am I under the wrong impression that these numbers should never decrease as they are cumulative?

**Comment by andrealouw** [comment]
suggested fix:
https://github.com/dsfsi/covid19za/issues/583

**Comment by horscroft-swish** [comment]
Closing in favour of linked fix.
