### ISSUE TITLE
Calculation query

### ISSUE THREAD

**Issue by philmassie** [dsfsi/covid19za#638]
Hi there.
Thanks for your work on the dashboard, been following it for some time.
Quick question please, not sure if this is the correct forum or if you have documentation elsewhere.
What's the calculation you use for the case finding rate chart? It's hard to see how it's at 17% but perhaps you're accounting for lags in results or something else?

I had a quick poke through your repo but couldn't see it, apologies if I missed it.

Thanks so much

**Comment by vukosim** [comment]
@philmassie 

This is the total/cumulative case finding rate, not daily.
