### ISSUE TITLE
[DATA] Possible data problem with recoveries in KZN 2020-08-14

### ISSUE THREAD

**Issue by lrossouw** [dsfsi/covid19za#643]
## Which Dataset
[data/covid19za_provincial_cumulative_timeline_recoveries.csv](https://github.com/dsfsi/covid19za/blob/master/data/covid19za_provincial_cumulative_timeline_recoveries.csv)

## Error Description

Data is captured correctly[ from the tweet,](https://twitter.com/nicd_sa/status/1294373407195377664/) but KZN recoveries jumped from 2020-08-13.  Need to see if some correction has been made.

## Suggested fixes
  1. Noting now, but wait and see if a correction is made by NICD?

**Comment by vukosim** [comment]
Thanks for bringing this up @lrossouw

**Comment by lrossouw** [comment]
They continued with the high figure on 15 August.  If it repeats tomorrow I will close this issue.

**Comment by lrossouw** [comment]
This seems to be a the new number.  Closing the issue.
