### ISSUE TITLE
Correctly citing the dataset

### ISSUE THREAD

**Issue by Baadier-Sydow** [dsfsi/covid19za#65]
Hi,

I saw that a citation for correctly citing the dataset has been added to the repos readme file.

I'm building a dashboard with the data and would like to check if I'm correctly citing the dataset on my [Data Sources](https://coronavirusdashboardsouthafrica.com/data) page?

**Comment by vukosim** [comment]
Link to the repo 

And then also write:

**Citation:** Marivate, Vukosi, de Waal, Alta, Combrink, Herkulaas, Lebogo, Ofentswe, Moodley, Shivan, Mtsweni, Nompumelelo, & Rikhotso, Vuthlari. (2020). Coronavirus disease (COVID-19) case data - South Africa [Data set]. Zenodo. http://doi.org/10.5281/zenodo.3723347

**Comment by Baadier-Sydow** [comment]
Sure thing will update that this evening.

**Comment by Baadier-Sydow** [comment]
Just a heads that I've made the change and it will go in with the next build.
