### ISSUE TITLE
[BUG] `Cases` Mispelling

### ISSUE THREAD

**Issue by mitchwongho** [dsfsi/covid19za#67]
**Describe the bug**
The word `cases` is misspelled as `casis` on page 2 of the dashboard

**To Reproduce**
1. Go to 'page #2' on the Daily Positive Casis graph

**Expected behavior**
`Casis` should be spelled as `Cases`

**Screenshots**
<img width="295" alt="Screenshot 2020-03-23 at 08 15 22" src="https://user-images.githubusercontent.com/885861/77287813-24417d80-6cdf-11ea-927e-1a3e6446a8ab.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: MacOS
 - Browser [e.g. chrome, safari] : Firefox
 - Version [e.g. 22]: 74

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vukosim** [comment]
Thanks, fixed.
