### ISSUE TITLE
[Feature]:Add Province to dataset

### ISSUE THREAD

**Issue by elolelo** [dsfsi/covid19za#671]
I wish to locate where the cases of hospital admissions are reported from .i.e. which provinces are associated with the data from these NICD survellience reports. 

Could it be possible, that from this [dataset](https://github.com/dsfsi/covid19za/blob/master/data/nicd_hospital_surveillance_data.csv),  an attribute for location gets added?

The dataset has a lot of useful info, thanks for consistently working on it.

**Comment by vukosim** [comment]
@vaibhavijames Could you assist?

**Comment by vaibhavijames** [comment]
Yes, I can! I can start adding the provincial data included in the NICD hospital surveillance reports.
