### ISSUE TITLE
[DATA] Incorrect data/Invalid Entry in covid19za_timeline_testing.csv

### ISSUE THREAD

**Issue by SimonRosen173** [dsfsi/covid19za#681]
## Which Dataset
covid19za_timeline_testing.csv

## Error Description
`cummulative_tests` value for 05-09-2020 is incorrect and of wrong format. It is entered as '3783 23' not '3783823'

## Suggested fixes
  1. Change `cummulative_tests` value for 05-09-2020 to '3 783 823'

**Comment by vukosim** [comment]
Thank you for catching this @SimonRosen173
