### ISSUE TITLE
What language/technology to learn to assist the DSFSI on Covid19ZA?

### ISSUE THREAD

**Issue by Baadier-Sydow** [dsfsi/covid19za#70]
Hi,

I'm busy using the data on my own side project but wanted to contribute some of my time back to the project to help out. 

What tech should I learn to help out?

I saw Go on the API?

**Comment by shikwambana** [comment]
Really good question. I would also like to know

**Comment by vukosim** [comment]
We currently Jupyter notebooks using python and the scraper and API are in GO. So for the moment that seems to be the two, we will keep using. Just a note that most of the work on the repo is on the data itself and making sure it's updated accurately. So more time is spent on validation than code.

**Comment by Baadier-Sydow** [comment]
I think I'll look at the Go then. Could add more functionality or help with that backlog for the API.

**Comment by vukosim** [comment]
We might need some automation when it comes to dealing with NICD and the
current lack of new data.

Also a csv to google sheets sync script would be useful. The dashboard
reads from a copy of the CSVs that are in a google sheet.

**Comment by Baadier-Sydow** [comment]
I'm going to assume you'll want a solution in Go and not something I'm familiar in already like JS?

**Comment by vukosim** [comment]
Use what you are comfortable and experienced in.

Vukosi

http://www.vima.co.za
http://www.twitter.com/vukosi

**Comment by Baadier-Sydow** [comment]
Sweet :) Do you have feature requests where I can get more details on whats required for the two you mentioned?

**Comment by elolelo** [comment]
Hi @Baadier-Sydow ,

Issue  #17  looks well detailed - once the current status on it is given maybe you can give it a  try

**Comment by Baadier-Sydow** [comment]
Will do :)
