### ISSUE TITLE
[DATA] Sedibeng deaths 18-10-2020

### ISSUE THREAD

**Issue by richardyoung00** [dsfsi/covid19za#735]
## Which Dataset
data/district_data/gp_sedibeng.csv

## Error Description
Death numbers for Sedibeng for 18-10-2020 are incorrect (they were reported incorrectly in the official media release)

Incorrect media release
https://twitter.com/GautengHealth/status/1318191574967291910

Prior and subsequent media releases show that the deaths remained on 330

https://twitter.com/GautengHealth/status/1317438574954991618
https://twitter.com/GautengHealth/status/1318538596085866501
https://twitter.com/GautengHealth/status/1318885765934403584

## Suggested fixes
  1. Update Sedibeng deaths for 18-10-2020 to 330
OR
  2. Remove the deaths value for Sedibeng for 18-10-2020 as it massively skews stats.

**Comment by shaze** [comment]
Thanks @richardyoung00  -- corrected.
