### ISSUE TITLE
NICD Provincial Data Scraper

### ISSUE THREAD

**Issue by lrossouw** [dsfsi/covid19za#767]
I will probably build a web scraper for the NICD data probably using R. 

Probably see it working as follows running in an hourly cron:
1. It will pull the covid19za repo and ensure it has all latest commits.
2. Read in the relevant CSVs
3. Then check for new pages in the format `https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-%d-%B-%Y/`.  E.g. [https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-6-nov-2020/](https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-6-nov-2020/).  This check will be done on the last date in the CSV + 1 (to avoid missing days).
3. It will scrape that page capturing the three tables (cases, tests, deaths & recoveries).
4. Sanity checks
5. Subject to passing checks, update the CSVs in the local repo and push directly to this repository.  Not keen to do automate the whole PR process too.

Anyone have any concerns?  

Sanity checks to stop the process on any of:

* Exceptions
* Non-numeric data
* Ensure numbers are strictly increasing.
* Province name checks
* Unrealistic increases?  10% on cumulative per day?

Thoughts?

**Comment by lrossouw** [comment]
I've done this.  An example of an automated commit in my fork:
https://github.com/lrossouw/covid19za/commit/af1390e16693170dea833dfa0181d088ddd24a27

**Comment by lrossouw** [comment]
My test above was successful processing 2 weeks data. Stopping 3 times due to NICD site changes but not once committing incorrect information.

See [the comparison](https://github.com/dsfsi/covid19za/compare/master...lrossouw:master#files_bucket).  You can see all that's different is the source url.

**Comment by lrossouw** [comment]
Closed by b0adcaf2ee170745b7536b7f4c5a549c803b886b

**Comment by vukosim** [comment]
Thanks @lrossouw this is so awesome. We can then reduce chances of error.

**Comment by lrossouw** [comment]
NP.  It should post within 15min or so of the page going up on NICD's site.

**Comment by dennisvnel** [comment]
This is really awesome. Well done.

**Comment by lrossouw** [comment]
Thanks, what I can also mention that is if the process fails on a particular day due to NICD messing with the url, or format of the page, someone can still capture manually.  The scraper will then notice this and move on to the next day.
