### ISSUE TITLE
[DATA] Corrputed file: https://github.com/dsfsi/covid19za/blob/master/data/covid19za_timeline_testing.csv

### ISSUE THREAD

**Issue by eguidotti** [dsfsi/covid19za#773]
## Which Dataset
https://github.com/dsfsi/covid19za/blob/master/data/covid19za_timeline_testing.csv

## Error Description
the file is corrupted: csv not formatted correctly

## Suggested fixes
  1. fix commas

**Comment by lrossouw** [comment]
I think c740e1263f158c48cbdef2240885a4cbf35ee1a6 closes this issue.  I built a scraper for that data, but the lines with multiple sources (with extra commas) confused my scraper.  I fixed it now. I also added private and public testing to this file, which I could easily scrape and thought it may be useful?

**Comment by eguidotti** [comment]
Thank you for the quick fix! It is working now 👍
