### ISSUE TITLE
Scrape and Update

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#800]
Hey @lrossouw wanted to check if there was an issue with yesterdays update, and also if people can help keep it going.

**Comment by lrossouw** [comment]
I didn't notice it had not updated.  Reason it did not process the output is because Recoveries in KZN moved from 157164 to 187266.  That's a big jump.  It stopped because a bigger than 10% increase in cumulative figures is flagged a potential error?

**Comment by vukosim** [comment]
From KZN sources it seems like it is correct. So we can put it through.
