### ISSUE TITLE
[Feature] Showcase Section in README - Urls changed for demo and repo for 'Covid-19 SA Data' project.

### ISSUE THREAD

**Issue by SimonRosen173** [dsfsi/covid19za#809]
**Is your feature request related to a problem? Please describe.**
In the main README for this repo under the showcase section the urls for my Covid19 visualizations website (Covid-19 SA Data) no longer correspond to the correct repo and demo url.

**Describe the solution you'd like**
Repos: There are now two repos that now correlate to my site. One that compromises the actual site (i.e. the js and html) located at https://github.com/SimonRosen173/Covid19SAData_JS and the other compromises the data processing code and data (which uses data from this repo). The later repo is located at https://github.com/SimonRosen173/Covid19SAData_Data. 

Demo: The url of the actual website has been changed to https://covid19data.co.za/

**Describe alternatives you've considered**
N/A

**Additional context**
Apologies for the wrong tag used as I believe none of the available tags corresponded to this particular issue.

**Comment by lrossouw** [comment]
I suggest you a pull request to make the changes you need in the URLs.

**Comment by vukosim** [comment]
Yes @lrossouw

**Comment by vukosim** [comment]
@lrossouw chicking about the scraping again.

**Comment by lrossouw** [comment]
Closed by 09e6c1d8ae7e8223f74a2e30971723647204c90b
