### ISSUE TITLE
[Feature] Capture Vaccination Figures

### ISSUE THREAD

**Issue by lrossouw** [dsfsi/covid19za#816]
Would we capture vaccinations to date in a CSV.  May be possible to automate from this page along with other numbers:
https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-24-mar-2021/

**Comment by vukosim** [comment]
Thanks @lrossouw

I will take a look this week to see what can be extracted automatically.

**Comment by vukosim** [comment]
Hey @lrossouw are you able to do your scrape and merge?

**Comment by vukosim** [comment]
@lrossouw  added this file https://github.com/dsfsi/covid19za/blob/master/data/covid19za_timeline_vaccination.csv

**Comment by lrossouw** [comment]
OK will see what I can do about capturing it automatically as part of my daily run.

**Comment by vukosim** [comment]
👍🏿

**Comment by lrossouw** [comment]
I believe this has been completed by 5314ff723a3952e7624b7deb7d555e4e34ae0544 and prior commits.  Should also be captured automatically going forward.
