### ISSUE TITLE
[DATA] Explain discrepancy between repo data and dashboard data

### ISSUE THREAD

**Issue by riazarbi** [dsfsi/covid19za#82]
## Which Dataset

Confirmed cases timeline; provincial cumulative timeline

## Error Description

I would expect the latest number of confirmed cases on the dashboard to be the same as the latest number in [provincial cases](https://github.com/dsfsi/covid19za/blob/master/data/covid19za_provincial_cumulative_timeline_confirmed.csv) or [timeline confirmed](https://github.com/dsfsi/covid19za/blob/master/data/covid19za_timeline_confirmed.csv)

But right now the repo cumulative cases is 554, and the dashboard says 709. Which suggests the dashboard does not pull from the repo

## Suggested fixes

Either 
 a. make the dashboard feed from the repo for common data source,
 b. Feed the repo from the data source behind the dashboard
 c. Document that they have different data sources in the README

At any rate I'd like come commentary on this discrepancy as it is tripping us up when ingesting the repo data.

**Comment by tomjuggler** [comment]
In addition the coronamap.co.za site also seems to have a different data source, despite it's [source code](https://github.com/JayWelsh/coronamap) clearly pointing to the [timeline confirmed](https://github.com/dsfsi/covid19za/blob/master/data/covid19za_timeline_confirmed.csv) data. I am a little confused, perhaps a change is in the works?

**Comment by mariaschuld** [comment]
I assume that the dashboard is now tracking the[ provincial file](https://github.com/dsfsi/covid19za/blob/master/data/covid19za_provincial_cumulative_timeline_confirmed.csv). Maybe this can explain the discrepancy?

**Comment by vukosim** [comment]
Yes that is true @mariaschuld. We cannot at the moment reliably infer new cases given the data from NICD, we are investigating ways to get better data from them @tomjuggler

**Comment by mariaschuld** [comment]
Cool, I hope NICD's data strategy will be fixed soon. Let me know if there is anything I can do @vukosim - also in terms of programming support.

**Comment by tomjuggler** [comment]
Thanks @mariaschuld @vukosim that's great I can just use the provincial data. Maybe the readme needs to reflect this? I was wondering how long the details would be possible to maintain once the numbers went up.

Working on an Android app, will share when done.
