### ISSUE TITLE
[DATA] Recovered cases CSV data

### ISSUE THREAD

**Issue by Shannanigans** [dsfsi/covid19za#83]
**Is your feature request related to a problem? Please describe.**
First off thank you for all the great work you guys have been doing. Currently recovered cases are not represent in the csv files. Do you plan to record this information? Assuming you do do you think it will be possible to map the recovered case to the `covid19za_timeline_confirmed.csv` case_id? In other words will we be able to determine which case_id from timeline_confirmed has recovered?

Out of scope of this issue but worth noting is that I am curious whether it is going to be possible to do the same with case fatalities?

There seems to be data access issue with the nicd and doh. Have they been contacted to request csv dumps or some alternative to scraping their reports?

**Describe the solution you'd like**
I would like for a file identical in structure to `covid19za_timeline_deaths.csv` to be populated for recovered case data.

**Comment by vukosim** [comment]
@Shannanigans it will be available later today.

**Comment by vukosim** [comment]
Available here https://github.com/dsfsi/covid19za/blob/master/data/covid19za_timeline_testing.csv

**Comment by Shannanigans** [comment]
Thank you
