### ISSUE TITLE
[Feature] FYI added tracking for Phase 2 Vaccinations

### ISSUE THREAD

**Issue by lrossouw** [dsfsi/covid19za#832]
Added tracking of Phase 2 Vaccinations in [data/covid19za_timeline_vaccination.csv](https://github.com/dsfsi/covid19za/blob/master/data/covid19za_timeline_vaccination.csv).

There are two additional columns in that file:
`vaccinations_sisonke` are the original Sisonke vaccinations.
`vaccinations_phase_2` are the Phase 2 vaccinations which are being reported separately.
`vaccinations` are the total vaccinations of the two and is the same name used before.  So hopefully any downstream reports will continue just working and will include both sources now.

In terms of NAs.  If they do not report Sisonke figures going forward I will leave `vaccinations_sisonke` blank but still fill in the total.  If they do not report Phase 2 vaccinations I will leave `vaccinations_phase_2` blank and also leave the total blank.

Hope that makes sense?

**Comment by vukosim** [comment]
LGTM @lrossouw

**Comment by lrossouw** [comment]
Ah looks good to me I guess?
