### ISSUE TITLE
[DATA] Duplicate data on 24 and 25 May 2021

### ISSUE THREAD

**Issue by janvdl** [dsfsi/covid19za#834]
## Which Dataset
covid19za_provincial_cumulative_timeline_confirmed.csv

## Error Description
25 May 2021 numbers are duplicates of 24 May 2021. 

## Suggested fixes
  1. Unsure of fix as NICD report for 25 May 2021 still reports the figures of 24 May 2021 (https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-25-may-2021/).

**Comment by janvdl** [comment]
Issue has been fixed in the source data, thank you to the person responsible.

**Comment by lrossouw** [comment]
My automated process captured what was in the report for that day which was a repeat.  I fixed this by using data from another dashboard.  See 95225c35066ba43ee22c2391c1c7781ddbb03947 for an explanation.
