### ISSUE TITLE
[Feature] Extend api to expose test timeline data

### ISSUE THREAD

**Issue by Shannanigans** [dsfsi/covid19za#85]
**Describe the solution you'd like**
Add an endpoint to the api that exposes testing timeline data.

**Comment by Vutlhari** [comment]
I will pick this up

**Comment by vukosim** [comment]
Thanks. Please also see the new columns in the different data especially testing and provincial csvs

**Comment by Vutlhari** [comment]
@Shannanigans the endpoint is now available [(https://covid-za-api.herokuapp.com/cases/timeline/tests)](https://covid-za-api.herokuapp.com/cases/timeline/tests)

cc @vukosim
