### ISSUE TITLE
[Feature] Show change in numbers in boxes at top

### ISSUE THREAD

**Issue by anelda** [dsfsi/covid19za#88]
**Is your feature request related to a problem? Please describe.**
The dashboard may be more informative if one can quickly see the daily change in numbers of infected, recovered, tests, etc with one glance without having to look at the plots.

**Describe the solution you'd like**
Show the change since the previous day in the blocks at the top of the dashboard

**Describe alternatives you've considered**
The graphs on https://coronamap.co.za/ show the change indicated with a + or - at the top of each plot.
The info blocks on the Hong Kong dashboard shows it with little triangles pointing up or down - https://chp-dashboard.geodata.gov.hk/covid-19/en.html

**Additional context**

**Comment by vukosim** [comment]
Working on it.

**Comment by anelda** [comment]
Thanks @vukosim :+1:
