### ISSUE TITLE
[Feature] Use dashboard to curb anxiety as case and casualty # grow

### ISSUE THREAD

**Issue by anelda** [dsfsi/covid19za#89]
**Is your feature request related to a problem? Please describe.**
The dashboard is doing a really good job of providing a visual overview of the underlying data, but I am concerned that there is a lot of emphasis on how things are escalating (which is the honest truth and important to see). 

I think people might increasingly be looking at the data for signs that lockdown and other measures are working and slowing spread down, but we know that this dashboard will debunk that idea over the next few weeks as more cases are detected due to spread (delayed because of incubation period) and increased testing capabilities, and as tally of casualties grow. 

The dashboard may play a role in due time to help people comply with implemented measures to curb the spread of COVID or it may play a role in causing people to lose faith (based on data) in the implemented measures.

**Describe the solution you'd like**
Can we organise the dashboard to emphasise the positives a bit more? Recoveries, active cases vs closed cases, severe vs mild cases. (We mustn't let people lose hope as the pandemic numbers get worse).

Is it possible to add annotations such as when the state of disaster was implemented, lockdown started, other measures put in place (e.g. when the high-throughput testing equipment goes online) to explain some of the data we're seeing. Also to help people who may not be that familiar with this dataset and data in general to get context and adjust expectations? 

Maybe show a shaded graph where we can show that we expect cases to grow drastically for the next few weeks at least before there could be a bit of a plateau.

Visualisations can drive anxiety (and the situation and data will cause anxiety regardless of how we visualise it), but I wonder if people have ideas to present the data as non-sensational but honestly as possible. 

**Additional context**
The broader public may look at the data with different contexts than someone who knows the data. I've heard from a number of people that the red map from Harvard and seeing the numbers ticking over is creating massive anxiety for them.

**Comment by vukosim** [comment]
Hey. Yes, will think about a couple of ways we can get this right.

**Comment by anelda** [comment]
Thanks! I'd be very happy to help brainstorm about how to do this or get data that can be added to annotate graphs. By no means my field of expertise, but let me know if I can help.

**Comment by anelda** [comment]
Useful post on the topic - more for mapping - https://www.esri.com/arcgis-blog/products/product/mapping/mapping-coronavirus-responsibly/

**Comment by vukosim** [comment]
I think we can remove the table on the first page and move it to 2nd page and use that real estate to look and empowering people locally. So maybe notes on flattening the curvy through staying at home etc.
