### ISSUE TITLE
[Feature] Automated scrapping of ministry releases

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#9]
**Is your feature request related to a problem? Please describe.**
Not a problem but an enhancement. 

**Describe the solution you'd like**
Use the ministry releases as an automated way to suggest new additions to the data. 

**Describe alternatives you've considered**
Currently manually populated.

**Comment by cishiv** [comment]
@vukosim I'd be happy to pick this up. I've started on a simple scraping solution based on the DOM format of the https://www.gov.za/newsroom page. Let me know if there are any specific requirements you have for the solution. 

Some initial thoughts:

- pull the _links_ out of https://www.gov.za/newsroom
- parse these links and apply 'sane' matching conditions to ensure that they are related to covid-19
- verify if the _links_ already appear on https://github.com/dsfsi/covid19za/blob/master/data/README.md, if so, do nothing
- if not, parse the 'case' data out of the link, and then update both the `README.md` and `.csv` file accordingly.
- automatically open a pull request to this repository with the branch format `data-update/{date}-{X}-case-COVID-19`
- add you as a reviewer on that pull request

In terms of running this automatically, my recommendation would be to run the scraper 6-12 hourly, perhaps deploying it on a heroku instance, or a digital ocean droplet. Let me know your thoughts. I will open a pull request once I have something tangible.

**Comment by vukosim** [comment]
Thanks that looks great. It can be a script.

**Comment by cishiv** [comment]
Hmm, looking at the complexity of programatically creating a pull request makes me think that it's a task better left for another day, for now, a rest API which allows you to download an updated file should suffice `hostname/get-updated-data` which returns `covid19za_timeline_confirmed.csv`

**Comment by vukosim** [comment]
Thats understood. A simple one would be a 

statement -> csv file (just with the cases in the statement).

On my side working to try to get someone from NICD to just publish their own CSV.

**Comment by vukosim** [comment]
This has been merged. Tested with mac. 

We just need to update the documentation and also dependencies.

**Comment by vukosim** [comment]
@cishiv NICD seems to now lag sacoronavirus.co.za, do we just update the url point?

**Comment by cishiv** [comment]
It might just work, it depends on how they are cataloging the information. Let me take a look after work today and I will post an update / new PR to allow scraping from both NICD and sacoronavirus @vukosim

**Comment by cishiv** [comment]
Updated the scraper with a new parser for sacoronavirus.co.za and made the command-line a bit friendlier https://github.com/dsfsi/covid19za/pull/40
