### ISSUE TITLE
[BUG] Scraper workflow error

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#904]
**Describe the bug**
![image](https://user-images.githubusercontent.com/836223/131288809-c563cfdf-0175-4c24-8ea0-18444ca6b333.png)

![image](https://user-images.githubusercontent.com/836223/131288852-19af17cb-a673-4cb4-83ac-939fb5b33971.png)

Please see @krokkie

**Comment by krokkie** [comment]
Fixed.   Limpopo's figures moved a bit on the pictures....
