### ISSUE TITLE
[BUG] Challenge with scraper (R)

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#908]
**Describe the bug**
Workflow fails multiple times . Issue with date resolution. 

**Expected behavior**
Workflow should run correctly.
**Screenshots**
![image](https://user-images.githubusercontent.com/836223/132121827-b0aafd79-9c0f-4528-afec-2bd34b113370.png)

**Comment by krokkie** [comment]
I have improved the script this morning;   Ultimately the OCR is prone to some errors, but the data is published buggy to start off with, making it slightly harder to just process using a straightforward ETL process.
