### ISSUE TITLE
[BUG] Run failed: Scrape provincial vaccinations data from sacoronavirus.co.za 

### ISSUE THREAD

**Issue by vukosim** [dsfsi/covid19za#909]
**Describe the bug**
See screenshot

**Screenshots**
![image](https://user-images.githubusercontent.com/836223/132121869-027fdb7e-b495-4f98-971d-a47a888763e5.png)

**Comment by vukosim** [comment]
@richardyoung00 please see above.

**Comment by richardyoung00** [comment]
@vukosim will take a look.
