### ISSUE TITLE
[DATA]

### ISSUE THREAD

**Issue by yuval-harpaz** [dsfsi/covid19za#930]
## Which Dataset
https://github.com/dsfsi/covid19za/blob/master/data/covid19za_provincial_cumulative_timeline_confirmed.csv

## Error Description
cumulative cases for FS (1808972) is 10 times too large for 2nd last entry 30-12-2021

## Suggested fixes
  1. find the actual value (188972 ?)

**Comment by krokkie** [comment]
Fixed this.   NICD revised number reported at https://www.nicd.ac.za/latest-confirmed-cases-of-covid-19-in-south-africa-31-december-2021/  typo.
