### ISSUE TITLE
Op-Ed and Letter to the editor

### ISSUE THREAD

**Issue by HerkulaasCombrink** [dsfsi/covid19za#931]
# Contributions needed for an Op-Ed and letter to the editor
@vukosim and @MikeMcMalace and another Professor in Public Health Philosophy are busy with putting together an important Op-Ed and a letter to the editor based on how data is shared with the public. 

## We want inputs
We would like inputs from different contributors to assist with this contribution. We are asking for inputs in the following ways:
Please send a reply on your thoughts or ideas
Please provide a high level overview of your inputs. 
The deadline for this is next Wednesday the 12th of January

We will create a shared Google Doc for all those interested so that we can work on this together. Authorship on the Letter to the editor with be shared, and your affiliations will be added if you wish to contribute.

## At a high level, here is the argument we are working on
The start of any disease outbreak requires an epidemiological birds-eye-view which includes three specific data points/variables: Time, Place, and number. Initially these are good enough to make decisions, and calculate inferences based on this information. However, as time continues (and the outbreak in not contained), the level of sophistication and detailed required to make informed decisions increases over time for the decision makers and members of the public. We recommend monitoring the correct data and using the correct visualizations and indicators to respond effectively. 

***Key Points***
The specific data sources that will be needed for the public to do the appropriate monitoring of the outbreak and elements within the healthcare system that needs to be shared, including hospitalization, will be explained so that the public can evaluate the impact of a disease outbreak/ public health concern.  These articles will outline the importance of data for public health measures in terms of disease outbreak and how information should be shared so that meaningful insights can be derived from both stakeholders managing the outbreak and members of the public.

## Everyone that is working in this repo is valuable, and we would love inputs from you all
@krokkie @lrossouw @shaze @lizelgreyling @elolelo @heerden @dmackie @richardyoung00 @codeChap and everyone else who contributed toward this Repo are welcome to submit a comment. A reminder again the deadline is next Wednesday the 12th of January

**Comment by lrossouw** [comment]
it's not clear what outcomes you want based on the above?

**Comment by MikeMcMalace** [comment]
@lrossouw, thank you for the question.

 The outcomes that we want:
- We are proposing a new way of sharing data and information to the public, in addition to what is already being shared
- We want people who are not data or tech savvy to understand what any disease outbreak means by looking at simplified visualisations  different from the current infographics shared with people
- Initial epidemiological responses focus on efforts led by three primary groups of variables, all related to Date, Time, and number. However, as outbreaks move to Epidemics etc. the level of sophistication required to make decisions (whether you are a public healthcare expert, or member of the Public) needs to be more nuanced and contextually relevant
- We would like to know if would you like to be part of the engagement so that we can setup a Google doc and invite you to contribute on there and give your inputs

**Comment by lizelgreyling** [comment]
This is very interesting, and sounds like something I would certainly like to assist with if I can. I am currently travelling though, and won't be able to contribute anything meaningful until 12 January. However, if any inputs during the morning of 12 January could still be worthwhile to you, please count me in.

**Comment by MikeMcMalace** [comment]
@lizelgreyling Most certainly

**Comment by MikeMcMalace** [comment]
Once we have all the contributors, we will create a separate document so that we can collaborative work on this within the week. We will invite everyone end of day on the 12th to the document

**Comment by MikeMcMalace** [comment]
Great, thank you for everyone's input. Please email me on Combrinkhm@ufs.ac.za if you want to be invited to the Google Doc to contribute to the output

**Comment by HerkulaasCombrink** [comment]
Good morning,

We are going to invite the people to the Google Doc for comments on the Op-Ed, after the argument is developed, we will move onto the letter to the editor.

Thank you for all the responses.

**Comment by vukosim** [comment]
@HerkulaasCombrink I suggest you put the link to the google doc here and ask people to ask for permission to access it.

**Comment by HerkulaasCombrink** [comment]
https://docs.google.com/document/d/1EcF2mNqXL3RRhNBaC1s8O7AmRW10ImHwSD_d7kDPyfw/edit

**Comment by HerkulaasCombrink** [comment]
Thank you everyone for your contributions thus far. 

This is a reminder to contribute toward the peace. 

Please contribute on the Google doc if you have not done so - so that you can be included in the Op-Ed. The Op-Ed is being drafted, so please use the link specified above for your contributions. If you did not contribute, you cannot be an author for the Op-Ed. We want to ensure that your valuable inputs are part of the process.

**Comment by shaze** [comment]
Sorry for the delay in responding. I have been on leave and back today. It will try to respond today

**Comment by shaze** [comment]
Thanks for the good start. Where are we aiming this for.

Having read it I think there are two issues: (1) the need for the underlying raw data to be released in a computer readable version and publicly accessible way; and (2) the need for public health authorities (and others) to be clear about how to present data in a way that is meaningful. 

These two points are of course related but I think that the paper needs to separate out these more -- at the moment it weaves between the two which is a little confusing. I would suggest we separate them out: (a) the need for raw data to be available -- the problems if not available and examples of what can be done with this (b) successes and failures of the communicating the data and examples of how things could be done differently and what the impact of choices made are (e.g., showing results per capita or the gross amount -- gives a very different perspective of what the burdens or problems are)

**Comment by HerkulaasCombrink** [comment]
@shaze we are writing the Op-Ed in the Conversation, the proposal for this is accepted and you will be added to the online editing platform once I have all the contributors handles.

I agree with your separation of these concepts in an academic paper, which is why we are submitting a letter to the editor. The part that was edited is just for the Op-Ed - hence the writing style etc. being a bit more emotive. Thank you for your comments prof. We can look online for the edits. If need be, we can also setup a brief virtual meeting with the group tomorrow just to make sure that we all agree and are comfortable with the argument.

**Comment by HerkulaasCombrink** [comment]
Dear everyone, nearly there with the Op-Ed. The academic article will follow this one, with a similar logic but with more detail.

Thank you for your contributions thus far. We are nearly finished with the Op-Ed. The updated article is in the Doc, and you all would have been invited to make edits online. There are three comments we still need to address. Please go through these as at 12pm on the 24th, I will submit this to the Conversation.

**Comment by shaze** [comment]
In case you haven't seen it

https://twitter.com/EricTopol/status/1496135944193425414/photo/1

**Comment by shaze** [comment]
Sorry -- this is a better link: https://www.nature.com/articles/d41586-022-00424-9
